/**
 * @file xini.c
 * @author Alan R. Rogers
 * @brief Test ini.c.
 * @copyright Copyright (c) 2014, Alan R. Rogers
 * <rogers@anthro.utah.edu>. This file is released under the Internet
 * Systems Consortium License, which can be found in file "LICENSE".
 */
#include "ini.h"
#include "misc.h"
#include "pophist.h"
#include <stdio.h>
#include <string.h>

#ifdef NDEBUG
#error "Unit tests must be compiled without -DNDEBUG flag"
#endif

#include <assert.h>

const char *assignments =
    "# Temporary file generated by xini\n"
    "dbl1 = %lf\n"
    "dbl2 = %le\n"
    "dbl3 = %lf\n"
    "int1 = %d\n"
    "int2 = %d\n" "int3 = %d\n" "str1 = %s\n" "str2 = %s\n" "str3 = %s\n";

int main(int argc, char **argv) {

    const char *fname = "xini.tmp";
    int         ok = 1;
    int         verbose = 0;

    switch (argc) {
    case 1:
        break;
    case 2:
        if(strncmp(argv[1], "-v", 2) != 0)
            eprintf("usage: xini [-v]\n");
        verbose = 1;
        break;
    default:
        eprintf("usage: xini [-v]\n");
    }

    double      dbl1 = 1.0, dbl2 = -999.123, dbl3 = 3.456789e10;
    int         int1 = 1, int2 = -999, int3 = 345678910;
    const char *str1 = "hello";
    const char *str2 = "123";
    const char *str3 =
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string "
        "this is a long string this is a long string this is a long string";
    double      t[] = { 1000.0, HUGE_VAL };
    double      twoN[] = { 1e5, 1e2 };

    double      x = 0;
    int         rval, i, cmp;
    char        buff[1000];

    memset(buff, 0, sizeof(buff));

    FILE       *fp = fopen(fname, "w");

    if(fp == NULL)
        eprintf("ERR@%s:%d: Can't open file \"%s\" for ouput\n",
                __FILE__, __LINE__, fname);
    fprintf(fp, assignments, dbl1, dbl2, dbl3, int1, int2, int3, str1, str2,
            str3);
    fprintf(fp, "PopHist\n");
    fprintf(fp, "#%9s %10s\n", "time", "twoN");
    for(i = 0; i < sizeof(t) / sizeof(double); ++i)
        fprintf(fp, "%10lf %10lf\n", t[i], twoN[i]);
    fclose(fp);

    Ini        *ini = Ini_new(fname);

    checkmem(ini, __FILE__, __LINE__);
    if(verbose)
        Ini_print(ini, stdout);

    assert(Ini_twoN0(ini) == twoN[0]);

    rval = Ini_setDbl(ini, "dbl1", &x, MANDATORY);
    assert(x == dbl1);

    rval = Ini_setDbl(ini, "dbl2", &x, MANDATORY);
    assert(x == dbl2);

    rval = Ini_setDbl(ini, "dbl3", &x, MANDATORY);
    assert(x == dbl3);

    rval = Ini_setInt(ini, "int1", &i, MANDATORY);
    assert(i == int1);

    rval = Ini_setInt(ini, "int2", &i, MANDATORY);
    assert(i == int2);

    rval = Ini_setInt(ini, "int3", &i, MANDATORY);
    assert(i == int3);

    rval = Ini_setString(ini, "str1", buff, sizeof(buff), MANDATORY);
    cmp = strcmp(buff, str1);
    assert(0 == cmp);

    rval = Ini_setString(ini, "str2", buff, sizeof(buff), MANDATORY);
    cmp = strcmp(buff, str2);
    assert(0 == cmp);

    rval = Ini_setString(ini, "str3", buff, sizeof(buff), MANDATORY);
    cmp = strcmp(buff, str3);
    assert(0 == cmp);

    EpochLink  *el = NULL;

    rval = Ini_setEpochLink(ini, &el, !MANDATORY);
    if(rval) {
        const EpochLink *el2 = el;

        int         epoch = 0;

        while(el2) {
            assert(dblEquals(t[epoch], EpochLink_duration(el2)));
            assert(dblEquals(twoN[epoch], EpochLink_twoN(el2)));
            el2 = EpochLink_next(el2);
            ++epoch;
        }
    } else
        printf("Ini_setEpochLink returned %d. FAIL\n", rval);

    EpochLink_free(el);
    Ini_free(ini);

    if(ok) {
        if(!verbose)
            remove(fname);
        unitTstResult("Ini", "OK");
    } else
        unitTstResult("Ini", "FAIL");

    return (ok ? 0 : EXIT_FAILURE);
}
/* Local Variables: */
/* mode: c */
/* End: */
