.TH "Assignment" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Assignment \- 
.PP
A linked list, each item representing the name and value of a variable whose value is assigned in an initialization file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.RI "\fIname of variable \fP"
.ti -1c
.RI "char * \fBvalue\fP"
.br
.RI "\fIvalue of variable \fP"
.ti -1c
.RI "struct \fBAssignment\fP * \fBnext\fP"
.br
.RI "\fInext \fBAssignment\fP in linked list \fP"
.in -1c
.SH "Detailed Description"
.PP 
A linked list, each item representing the name and value of a variable whose value is assigned in an initialization file\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
