.TH "BootConf" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BootConf \- 
.PP
Contains the data for a bootstrap confidence interval\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBnReps\fP"
.br
.ti -1c
.RI "long \fBblockLength\fP"
.br
.ti -1c
.RI "int \fBnBins\fP"
.br
.ti -1c
.RI "unsigned \fBspecDim\fP"
.br
.ti -1c
.RI "double \fBconfidence\fP"
.br
.ti -1c
.RI "double * \fBlow\fP"
.br
.ti -1c
.RI "double * \fBhigh\fP"
.br
.ti -1c
.RI "double * \fBloSpec\fP"
.br
.ti -1c
.RI "double * \fBhiSpec\fP"
.br
.ti -1c
.RI "double * \fBsep_cm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the data for a bootstrap confidence interval\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
