.TH "boot2tbl.c" 3 "Wed May 28 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
boot2tbl.c \- 
.PP
Read a block bootstrap file, as produced by eld, and print it in tabular form\&. 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include 'boot\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (void)"
.br
.RI "\fIPrint usage message and abort\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Read a block bootstrap file, as produced by eld, and print it in tabular form\&. 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP


\fBAuthor:\fP
.RS 4
Alan R\&. Rogers 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void \fBusage\fP (void)"
.PP
Print usage message and abort\&. Parse output of MS, produce gtp format, the input for eld\&. 
.PP
Referenced by check_tn(), and vcf2gtp\&.Map::next()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
