.TH "domacs" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
domacs \- Run Gary Chen's program, 'MACS'
.PP
\fBAuthor:\fP
.RS 4
Alan R\&. Rogers \fBdomacs\&.py\fP: Use MACS to simulate a history of constant population size\&. =====================================================================
.RE
.PP
Usage: \fBdomacs\&.py\fP [-r or --run] output_file_basename
.PP
Chen doesn't say how time is scaled\&. I'm guessing that units are 4N generations, because that is how recombination rate and mutation are scaled\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP

