.TH "domacs.py" 3 "Wed May 28 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
domacs.py \- Run Gary Chen's program, 'MACS'
.PP
 
.PP
\fBAuthor:\fP
.RS 4
Alan R\&. Rogers 
.SH "domacs\&.py: Use MACS to simulate a history of constant population size\&. "
.PP
.RE
.PP
.PP
Usage: domacs\&.py [-r or --run] output_file_basename
.PP
Chen doesn't say how time is scaled\&. I'm guessing that units are 4N generations, because that is how recombination rate and mutation are scaled\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers rogers@anthro.utah.edu\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP

