.TH "domacs.py" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
domacs.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBdomacs\&.usage\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdomacs\&.runprogram\fP = False"
.br
.ti -1c
.RI "\fBdomacs\&.obasename\fP = None"
.br
.ti -1c
.RI "int \fBdomacs\&.retain\fP = 100"
.br
.ti -1c
.RI "string \fBdomacs\&.outputfile\fP = obasename+'\&.macs'"
.br
.ti -1c
.RI "string \fBdomacs\&.errfile\fP = obasename+'\&.macserr'"
.br
.ti -1c
.RI "string \fBdomacs\&.iniFile\fP = 'ldpsiz\&.ini'"
.br
.ti -1c
.RI "list \fBdomacs\&.twoN0\fP = ph[0]"
.br
.ti -1c
.RI "list \fBdomacs\&.twoN1\fP = ph[1]"
.br
.ti -1c
.RI "list \fBdomacs\&.t0\fP = ph[0]"
.br
.ti -1c
.RI "tuple \fBdomacs\&.twoNsmp\fP = int(a['twoNsmp'])"
.br
.ti -1c
.RI "tuple \fBdomacs\&.basepairs\fP = float(a['basepairs'])"
.br
.ti -1c
.RI "tuple \fBdomacs\&.mutation\fP = float(a['mutation'])"
.br
.ti -1c
.RI "tuple \fBdomacs\&.recombination\fP = float(a['recombination'])"
.br
.ti -1c
.RI "string \fBdomacs\&.cmd\fP = 'macs %s %s'"
.br
.ti -1c
.RI "float \fBdomacs\&.time\fP = 0\&.0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
