.TH "EpochLink" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EpochLink \- 
.PP
Population history represented as a linked list of epochs\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBEpochLink\fP * \fBnext\fP"
.br
.ti -1c
.RI "double \fBt\fP"
.br
.ti -1c
.RI "double \fBtwoN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Population history represented as a linked list of epochs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
