.TH "FileIndex" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileIndex \- 
.PP
Index of SNPs in a file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBchunksAllocated\fP"
.br
.ti -1c
.RI "long \fBptrsAllocated\fP"
.br
.ti -1c
.RI "long \fBnSNPs\fP"
.br
.ti -1c
.RI "\fBSNPLoc\fP ** \fBsnploc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Index of SNPs in a file\&. 

Allows translation between the \fBSNP\fP's index, mappos, and seekpos\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
