.TH "HillData" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HillData \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBydim\fP"
.br
.ti -1c
.RI "double \fBy\fP [DIM]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
