.TH "Ini" 3 "Wed May 14 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ini \- 
.PP
The information read from an initialization file\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBEpochLink\fP * \fBepochList\fP"
.br
.RI "\fIpopulation history \fP"
.ti -1c
.RI "\fBAssignment\fP * \fBa\fP"
.br
.RI "\fIlinked list of assignments \fP"
.in -1c
.SH "Detailed Description"
.PP 
The information read from an initialization file\&. 



.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
