.TH "ini.py" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ini.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBini\&.Epoch\fP"
.br
.RI "\fIRepresents an epoch of population history, within which the population's characteristics do not change\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBini\&.isfinite\fP"
.br
.ti -1c
.RI "def \fBini\&.readIni\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBini\&.s\fP = 'Epoch %2d:'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
