.TH "Job" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Job \- 
.PP
A single job in the queue\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBJob\fP * \fBnext\fP"
.br
.RI "\fIpointer to next job in queue \fP"
.ti -1c
.RI "void * \fBparam\fP"
.br
.RI "\fIpointer to data for current job \fP"
.ti -1c
.RI "int(* \fBjobfun\fP )(void *\fBparam\fP)"
.br
.RI "\fIpointer to function that undertakes current job \fP"
.in -1c
.SH "Detailed Description"
.PP 
A single job in the queue\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
