.TH "LocRef" 3 "Wed May 14 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LocRef \- 
.PP
\fBLocRef\fP facilitates using a single memory block to allocate a structure and all the arrays within it\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <locref\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBcurr\fP"
.br
.ti -1c
.RI "size_t \fBstart\fP [LOCREFMAX]"
.br
.ti -1c
.RI "size_t \fBend\fP [LOCREFMAX]"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLocRef\fP facilitates using a single memory block to allocate a structure and all the arrays within it\&. 

This trick is called the 'struct hack' in C programming\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
