.TH "locref.h" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
locref.h \- 
.PP
Header for \fBlocref\&.c\fP 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. 
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include 'typedefs\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBLocRef\fP"
.br
.RI "\fI\fBLocRef\fP facilitates using a single memory block to allocate a structure and all the arrays within it\&. \fP"
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBLOCREFMAX\fP   100"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLocRef_init\fP (\fBLocRef\fP *lr)"
.br
.RI "\fIFill \fBLocRef\fP structure with zeroes\&. \fP"
.ti -1c
.RI "void \fBLocRef_add\fP (\fBLocRef\fP *lr, size_t size)"
.br
.RI "\fIAdd an entry of specified size bytes to the \fBLocRef\fP table\&. \fP"
.ti -1c
.RI "size_t \fBLocRef_size\fP (\fBLocRef\fP *lr)"
.br
.RI "\fITotal size of memory block to be allocated\&. \fP"
.ti -1c
.RI "void \fBLocRef_setNext\fP (\fBLocRef\fP *lr, int i)"
.br
.RI "\fISet the index to be returned by the next call to LocRef_next\&. \fP"
.ti -1c
.RI "void * \fBLocRef_next\fP (\fBLocRef\fP *lr, void *base)"
.br
.RI "\fIReturn a pointer to the next object in \fBLocRef\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Header for \fBlocref\&.c\fP 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. 
.RE
.PP


Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.SH "Function Documentation"
.PP 
.SS "void \fBLocRef_add\fP (\fBLocRef\fP *lr, size_tbytes)"
.PP
Add an entry of specified size bytes to the \fBLocRef\fP table\&. 
.SS "void \fBLocRef_init\fP (\fBLocRef\fP *lr)"
.PP
Fill \fBLocRef\fP structure with zeroes\&. 
.SS "void \fBLocRef_setNext\fP (\fBLocRef\fP *lr, inti)"
.PP
Set the index to be returned by the next call to LocRef_next\&. 
.SS "size_t \fBLocRef_size\fP (\fBLocRef\fP *lr)"
.PP
Total size of memory block to be allocated\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
