.TH "locref.c" 3 "Wed May 28 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
locref.c \- 
.PP
\fBLocRef\fP is a class that facilitates using a single memory block to allocate a structure and all the arrays within it\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include 'locref\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBLocRef_init\fP (\fBLocRef\fP *lr)"
.br
.RI "\fIFill \fBLocRef\fP structure with zeroes\&. \fP"
.ti -1c
.RI "void \fBLocRef_add\fP (\fBLocRef\fP *lr, size_t bytes)"
.br
.RI "\fIAdd an entry of specified size bytes to the \fBLocRef\fP table\&. \fP"
.ti -1c
.RI "size_t \fBLocRef_size\fP (\fBLocRef\fP *lr)"
.br
.RI "\fITotal size of memory block to be allocated\&. \fP"
.ti -1c
.RI "void \fBLocRef_setNext\fP (\fBLocRef\fP *lr, int i)"
.br
.RI "\fISet the index to be returned by the next call to LocRef_next\&. \fP"
.ti -1c
.RI "void * \fBLocRef_next\fP (\fBLocRef\fP *lr, void *base)"
.br
.RI "\fIReturn a pointer to the next object in \fBLocRef\fP\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBLocRef\fP is a class that facilitates using a single memory block to allocate a structure and all the arrays within it\&. 

 \fBLocRef\fP is facilitates using a single memory block to allocate a structure and all the arrays within it\&. This trick is called the 'struct hack' in C programming\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void \fBLocRef_add\fP (\fBLocRef\fP *lr, size_tbytes)"
.PP
Add an entry of specified size bytes to the \fBLocRef\fP table\&. 
.SS "void \fBLocRef_init\fP (\fBLocRef\fP *lr)"
.PP
Fill \fBLocRef\fP structure with zeroes\&. 
.SS "void \fBLocRef_setNext\fP (\fBLocRef\fP *lr, inti)"
.PP
Set the index to be returned by the next call to LocRef_next\&. 
.SS "size_t \fBLocRef_size\fP (\fBLocRef\fP *lr)"
.PP
Total size of memory block to be allocated\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
