.TH "macs2gtp.py" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
macs2gtp.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmacs2gtp\&.usage\fP"
.br
.RI "\fIPrint usage message and exit\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmacs2gtp\&.recombination\fP = None"
.br
.ti -1c
.RI "list \fBmacs2gtp\&.twoN0\fP = ph[0]"
.br
.ti -1c
.RI "int \fBmacs2gtp\&.i\fP = 1"
.br
.ti -1c
.RI "list \fBmacs2gtp\&.datafile\fP = sys\&.argv[i]"
.br
.ti -1c
.RI "tuple \fBmacs2gtp\&.infile\fP = open(datafile)"
.br
.ti -1c
.RI "tuple \fBmacs2gtp\&.line\fP = infile\&.readline()"
.br
.ti -1c
.RI "tuple \fBmacs2gtp\&.fourNc\fP = float(line[i])"
.br
.ti -1c
.RI "tuple \fBmacs2gtp\&.err\fP = abs(fourNc - recombination*2*twoN0)"
.br
.ti -1c
.RI "tuple \fBmacs2gtp\&.nnucleotides\fP = int(round(float(line[3])))"
.br
.ti -1c
.RI "int \fBmacs2gtp\&.lineno\fP = 0"
.br
.ti -1c
.RI "tuple \fBmacs2gtp\&.nfields\fP = len(line)"
.br
.ti -1c
.RI "tuple \fBmacs2gtp\&.nucpos\fP = int(round(nnucleotides*float(line[2])))"
.br
.ti -1c
.RI "float \fBmacs2gtp\&.centimorgan\fP = nucpos*recombination*100\&.0"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
