.TH "macs2gtp" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
macs2gtp \- Parse output of macs, produce gtp format, the input for eld\&.
.PP
.SH "\fBmacs2gtp\&.py\fP, a program that converts \fCmacs\fP output into \&.gtp format "
.PP
.PP
.PP
.nf
Usage: macs2gtp.py [options] \<input file\> 
where options may include:
  -R \<x\> : set recombination rate for adjacent sites
.fi
.PP
.PP
For example, 
.PP
.nf
macs2gtp.py -R 1e-8 macs.out > macs.gtp

.fi
.PP
.PP
Would read file \fCmacs\&.out\fP, generate map distances assuming a recombination rate of 1e-8 per nucleotide, and write the output into macs\&.gtp\&.
.PP
If the recombination rate is not specified, \fC\fBmacs2gtp\&.py\fP\fP tries to get it from the initialization file \fCldpsiz\&.ini\fP\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers rogers@anthro.utah.edu\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP

