.TH "mcmcld" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mcmcld \- `mcmcld` uses Markov-Coupled Markov-Chain Monte Carlo (MCMCMC) to estimate the cost function $\sigma_d^2$\&.
.PP
mcmcld, MCMCMC estimates of population history from $\sigma_d^2$ ====================================================================
.PP
This program needs work\&. Don't trust the current version\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP

