.TH "ms2gtp.c" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ms2gtp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include 'ini\&.h'\fP
.br
\fC#include 'tokenizer\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (void)"
.br
.RI "\fIParse output of MS, produce gtp format, the input for eld\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
