.TH "ODE" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ODE \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const gsl_odeiv2_step_type * \fBstepType\fP"
.br
.ti -1c
.RI "gsl_odeiv2_step * \fBstepFun\fP"
.br
.ti -1c
.RI "gsl_odeiv2_control * \fBctrl\fP"
.br
.ti -1c
.RI "gsl_odeiv2_evolve * \fBevolve\fP"
.br
.ti -1c
.RI "\fBModel\fP * \fBmodel\fP"
.br
.ti -1c
.RI "int \fBydim\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "struct \fBdydt_params\fP \fBdydtPar\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
