.TH "preld.c" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
preld.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <gsl/gsl_errno\&.h>\fP
.br
\fC#include <gsl/gsl_matrix\&.h>\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include 'pophist\&.h'\fP
.br
\fC#include 'tokenizer\&.h'\fP
.br
\fC#include 'hill\&.h'\fP
.br
\fC#include 'hayes\&.h'\fP
.br
\fC#include 'strobeck\&.h'\fP
.br
\fC#include 'model\&.h'\fP
.br
\fC#include 'ini\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (void)"
.br
.ti -1c
.RI "void \fBcheck_tn\fP (double t, double n)"
.br
.RI "\fIMake sure values of t and N are valid\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
