.TH "sald.c" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sald.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <assert\&.h>\fP
.br
\fC#include <gsl/gsl_rng\&.h>\fP
.br
\fC#include <gsl/gsl_randist\&.h>\fP
.br
\fC#include <float\&.h>\fP
.br
\fC#include <getopt\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br
\fC#include <limits\&.h>\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include 'boot\&.h'\fP
.br
\fC#include 'pophist\&.h'\fP
.br
\fC#include 'sasimplex\&.h'\fP
.br
\fC#include 'tokenizer\&.h'\fP
.br
\fC#include 'jobqueue\&.h'\fP
.br
\fC#include 'hill\&.h'\fP
.br
\fC#include 'ini\&.h'\fP
.br
\fC#include 'model\&.h'\fP
.br
\fC#include 'assign\&.h'\fP
.br
\fC#include 'annealsched\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTaskArg\fP"
.br
.RI "\fIThe total job is divided into tasks, which are placed on a queue\&. \fP"
.ti -1c
.RI "struct \fBCostPar\fP"
.br
.RI "\fIParameters of cost function--that which is minimized\&. \fP"
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDPRINTF\fP(arg)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (void)"
.br
.ti -1c
.RI "int \fBread_data\fP (FILE *ifp, int nbins, double *cm, double *sigdsq)"
.br
.RI "\fIRead the data file produced by eld\&. \fP"
.ti -1c
.RI "\fBTaskArg\fP * \fBTaskArg_new\fP (unsigned task, unsigned seed, int nbins, double u, double ftol, double xtol, double *stepsize, \fBAnnealSched\fP *sched, double *loBnd, double *hiBnd, double *hiInit, double odeAbsTol, double odeRelTol, int nPerTmptr, int verbose, double *sigdsq_obs, double *c, \fBModel\fP *model, \fBPopHist\fP *ph_init, int randomStart)"
.br
.RI "\fIConstruct a new \fBTaskArg\fP\&. \fP"
.ti -1c
.RI "void \fBTaskArg_free\fP (\fBTaskArg\fP *targ)"
.br
.ti -1c
.RI "int \fBtaskfun\fP (void *varg)"
.br
.ti -1c
.RI "static double \fBcostFun\fP (const gsl_vector *x, void *varg)"
.br
.RI "\fISum of differences between observed and expected sigma_d^2 vectors\&. \fP"
.ti -1c
.RI "void \fBCostPar_print\fP (\fBCostPar\fP *cp)"
.br
.ti -1c
.RI "\fBTaskArg\fP * \fBTaskArg_best\fP (\fBTaskArg\fP **tpvec, int n)"
.br
.RI "\fIGiven a vector of \fBTaskArg\fP pointers, return a pointer to the one with lowest cost among those that have converged\&. \fP"
.ti -1c
.RI "void \fBprHeader\fP (\fBPopHist\fP *ph)"
.br
.RI "\fIPrint header\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBsetSimplexVersion\fP"
.br
.ti -1c
.RI "pthread_mutex_t \fBstdoutLock\fP = PTHREAD_MUTEX_INITIALIZER"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static double costFun (const gsl_vector *x, void *varg)\fC [static]\fP"

.PP
Sum of differences between observed and expected sigma_d^2 vectors\&. 
.PP
\fBParameters:\fP
.RS 4
\fIph\fP Current population history 
.br
\fIu\fP mutation rate per site per generation 
.br
\fInbins\fP Number of values in vectors obs and c 
.br
\fIsigdsq\fP Vector of nbins values, the observed values of sigdsq\&. 
.br
\fIc\fP Vector of nbins values, the recombination rates associated with the values in sigdsq\&. 
.RE
.PP

.PP
References ODE_ldVec(), PopHist_nParams(), PopHist_paramName(), PopHist_paramValue(), PopHist_print(), and vector_to_PopHist()\&.
.SS "int read_data (FILE *ifp, intnbins, double *cm, double *sigdsq)"

.PP
Read the data file produced by eld\&. 
.PP
\fBParameters:\fP
.RS 4
\fIifp\fP Points to file produced by eld\&. 
.br
\fInbins\fP The length of all arrays\&. 
.br
\fIcm\fP An array giving the average separation (in centimorgans) between pairs of SNPs within the various bins\&. 
.br
\fIsigdsq\fP An array of estimates of sigma_d^2\&.
.RE
.PP
\fBReturns:\fP
.RS 4
number of lines read 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
