.TH "sasimplex_state_t" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sasimplex_state_t \- 
.PP
The state of the minimizer\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "gsl_matrix * \fBx1\fP"
.br
.ti -1c
.RI "gsl_vector * \fBf1\fP"
.br
.ti -1c
.RI "gsl_vector * \fBws1\fP"
.br
.ti -1c
.RI "gsl_vector * \fBws2\fP"
.br
.ti -1c
.RI "gsl_vector * \fBcenter\fP"
.br
.ti -1c
.RI "gsl_vector * \fBdelta\fP"
.br
.ti -1c
.RI "gsl_vector * \fBxmc\fP"
.br
.ti -1c
.RI "gsl_vector * \fBlbound\fP"
.br
.ti -1c
.RI "gsl_vector * \fBubound\fP"
.br
.ti -1c
.RI "gsl_vector * \fBstep_size\fP"
.br
.ti -1c
.RI "double \fBS2\fP"
.br
.ti -1c
.RI "double \fBtemperature\fP"
.br
.ti -1c
.RI "double \fBbestEver\fP"
.br
.ti -1c
.RI "unsigned \fBseedSet\fP"
.br
.ti -1c
.RI "unsigned \fBseed\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The state of the minimizer\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
