.TH "SNP" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SNP \- 
.PP
The \fBSNP\fP class represents a single nucleotide polymorphism\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <snp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBmappos\fP"
.br
.ti -1c
.RI "unsigned char * \fBgtype\fP"
.br
.ti -1c
.RI "unsigned \fBnGtype\fP"
.br
.ti -1c
.RI "long \fBndx\fP"
.br
.ti -1c
.RI "double \fBsum\fP"
.br
.ti -1c
.RI "double \fBp\fP"
.br
.ti -1c
.RI "double \fBpq\fP"
.br
.ti -1c
.RI "int \fBbootreps\fP"
.br
.ti -1c
.RI "unsigned * \fBmultiplicity\fP"
.br
.ti -1c
.RI "struct \fBSNP\fP * \fBprev\fP"
.br
.ti -1c
.RI "int * \fBmultiplicity\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBSNP\fP class represents a single nucleotide polymorphism\&. 

Estimate the site frequency spectrum\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2015, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&.
.RE
.PP
Definition is provided openly here (rather than hidden in \fBspecscan\&.c\fP) so that functions can be inlined\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2015, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
