.TH "SNP" 3 "Wed May 28 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SNP \- 
.PP
Estimate the linkage disequilibrium (LD) between single nucleotide polymorphisms (SNPs) as a function of the map distance between those SNPs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBmappos\fP"
.br
.ti -1c
.RI "unsigned char * \fBgtype\fP"
.br
.ti -1c
.RI "unsigned \fBnGtype\fP"
.br
.ti -1c
.RI "long \fBndx\fP"
.br
.ti -1c
.RI "double \fBsum\fP"
.br
.ti -1c
.RI "double \fBp\fP"
.br
.ti -1c
.RI "double \fBpq\fP"
.br
.ti -1c
.RI "int \fBbootreps\fP"
.br
.ti -1c
.RI "int * \fBmultiplicity\fP"
.br
.ti -1c
.RI "struct \fBSNP\fP * \fBprev\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estimate the linkage disequilibrium (LD) between single nucleotide polymorphisms (SNPs) as a function of the map distance between those SNPs\&. 

Definition is provided openly here (rather than hidden in \fBwindow\&.h\fP) so that functions can be inlined\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
