.TH "SNPLoc" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SNPLoc \- 
.PP
The location of a \fBSNP\fP in a file and on a chromosome\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "long \fBseekpos\fP"
.br
.ti -1c
.RI "double \fBmappos\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The location of a \fBSNP\fP in a file and on a chromosome\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
