.TH "sums.h" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sums.h \- 
.PP
Header for \fBsums\&.c\fP 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBdotprod\fP (double *x, double *y, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBdotprod_int\fP (unsigned *x, unsigned *y, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBdotprod_char\fP (unsigned char *x, unsigned char *y, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBsum_and_int\fP (unsigned *x, unsigned *y, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBsum_and_char\fP (unsigned char *x, unsigned char *y, unsigned n)"
.br
.ti -1c
.RI "unsigned long \fBsum_long\fP (unsigned long *x, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBsum_int\fP (unsigned *x, unsigned n)"
.br
.ti -1c
.RI "double \fBsum_double\fP (double *x, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBsum_char\fP (const unsigned char *x, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBdotprodDiploid\fP (unsigned char *x, unsigned char *y, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBsumDiploid\fP (const unsigned char *x, unsigned n)"
.br
.ti -1c
.RI "void \fBtrickOptimizer\fP (void)"
.br
.ti -1c
.RI "unsigned long \fBsum_long_slow\fP (unsigned long *x, unsigned n)"
.br
.ti -1c
.RI "double \fBdotprod_slow\fP (double *x, double *y, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBdotprod_int_slow\fP (unsigned *x, unsigned *y, unsigned n)"
.br
.ti -1c
.RI "unsigned \fBdotprod_char_slow\fP (unsigned char *x, unsigned char *y, unsigned n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for \fBsums\&.c\fP 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP


\fBAuthor:\fP
.RS 4
Alan R\&. Rogers 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
