.TH "Tabulation" 3 "Wed May 28 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tabulation \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnbins\fP"
.br
.ti -1c
.RI "double \fBwindowcm\fP"
.br
.ti -1c
.RI "double \fBbins_per_cm\fP"
.br
.ti -1c
.RI "long unsigned * \fBnobs\fP"
.br
.ti -1c
.RI "double * \fBsep_cm\fP"
.br
.ti -1c
.RI "double * \fBnumerator\fP"
.br
.ti -1c
.RI "double * \fBdenominator\fP"
.br
.ti -1c
.RI "double * \fBrsq\fP"
.br
.ti -1c
.RI "long unsigned \fBoldNobs\fP [2]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
