.TH "tabulation.h" 3 "Wed May 28 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tabulation.h \- 
.PP
Header for tabulation\&.c 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'typedefs\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBTabulation\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTabulation\fP * \fBTabulation_new\fP (double windowcm, int nbins)"
.br
.ti -1c
.RI "\fBTabulation\fP * \fBTabulation_dup\fP (\fBTabulation\fP *old)"
.br
.ti -1c
.RI "void \fBTabulation_free\fP (\fBTabulation\fP *tab)"
.br
.ti -1c
.RI "void \fBTabulation_plus_equals\fP (\fBTabulation\fP *x, const \fBTabulation\fP *y)"
.br
.ti -1c
.RI "void \fBTabulation_print\fP (\fBTabulation\fP *tab, FILE *ofp)"
.br
.ti -1c
.RI "int \fBTabulation_report\fP (\fBTabulation\fP *tab, double *sep_cm, long unsigned *nobs, double *sigdsq, double *rsq)"
.br
.ti -1c
.RI "double \fBTabulation_sigdsq\fP (\fBTabulation\fP *tab, int bin, double *sep_cm, long unsigned *nobs)"
.br
.ti -1c
.RI "double \fBTabulation_rsq\fP (\fBTabulation\fP *tab, int bin, double *sep_cm, long unsigned *nobs)"
.br
.ti -1c
.RI "double \fBTabulation_denom\fP (\fBTabulation\fP *tab, int bin, double *sep_cm, long unsigned *nobs)"
.br
.ti -1c
.RI "long unsigned \fBTabulation_rawCounts\fP (\fBTabulation\fP *tab, int bin, double *numerator, double *denominator, double *sumRsq, double *sep_cm)"
.br
.ti -1c
.RI "long unsigned \fBTabulation_nObs\fP (const \fBTabulation\fP *tab, int i)"
.br
.ti -1c
.RI "int \fBTabulation_equals\fP (const \fBTabulation\fP *x, const \fBTabulation\fP *y)"
.br
.ti -1c
.RI "void \fBTabulation_dump\fP (const \fBTabulation\fP *tab, FILE *ofp)"
.br
.ti -1c
.RI "\fBTabulation\fP * \fBTabulation_restore\fP (FILE *ifp)"
.br
.ti -1c
.RI "int \fBTabulation_isfinite\fP (const \fBTabulation\fP *tab)"
.br
.ti -1c
.RI "void \fBTabulation_sanityCheck\fP (\fBTabulation\fP *tab, const char *file, int line)"
.br
.ti -1c
.RI "int \fBTabulation_overflow\fP (\fBTabulation\fP *tab)"
.br
.ti -1c
.RI "void \fBTabulation_test\fP (int verbose)"
.br
.ti -1c
.RI "static void \fBTabulation_record\fP (\fBTabulation\fP *tab, double Dsq, double pqpq, double sep_cm, unsigned wgt)"
.br
.ti -1c
.RI "static int \fBgetBin\fP (double sep_cm, double bins_per_cm)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for tabulation\&.c 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP


\fBAuthor:\fP
.RS 4
Alan R\&. Rogers 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
