.TH "TaskArg" 3 "Wed May 14 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskArg \- 
.PP
The total job is divided into tasks, which are placed on a queue\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBtask\fP"
.br
.ti -1c
.RI "unsigned \fBseed\fP"
.br
.ti -1c
.RI "int \fBnbins\fP"
.br
.ti -1c
.RI "size_t \fBndim\fP"
.br
.ti -1c
.RI "double \fBu\fP"
.br
.ti -1c
.RI "double \fBftol\fP"
.br
.ti -1c
.RI "double \fBxtol\fP"
.br
.ti -1c
.RI "\fBAnnealSched\fP * \fBsched\fP"
.br
.ti -1c
.RI "double * \fBstepsize\fP"
.br
.ti -1c
.RI "int \fBnPerTmptr\fP"
.br
.ti -1c
.RI "int \fBrandomStart\fP"
.br
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "double * \fBsigdsq_obs\fP"
.br
.ti -1c
.RI "double * \fBc\fP"
.br
.ti -1c
.RI "double * \fBloBnd\fP"
.br
.ti -1c
.RI "double * \fBhiBnd\fP"
.br
.ti -1c
.RI "double * \fBhiInit\fP"
.br
.ti -1c
.RI "\fBODE\fP * \fBode\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "double \fBsimplexSize\fP"
.br
.ti -1c
.RI "\fBPopHist\fP * \fBph\fP"
.br
.ti -1c
.RI "double \fBcost\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The total job is divided into tasks, which are placed on a queue\&. 

Each thread takes a task from the queue and executes it\&. This continues until the queue is empty\&. The \fBTaskArg\fP structure contains the parameters of a single task\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
