.TH "typedefs.h" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
typedefs.h \- 
.PP
Typedefs of all classes 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBdydt_params\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBINIFILE\fP   'ldpsiz\&.ini'"
.br
.ti -1c
.RI "#define \fBFILENAMESIZE\fP   200"
.br
.ti -1c
.RI "#define \fBVERBOSE\fP   1"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct MinimizerResult \fBMinimizerResult\fP"
.br
.ti -1c
.RI "typedef struct ObjLink \fBObjLink\fP"
.br
.ti -1c
.RI "typedef struct SeqDatPar \fBSeqDatPar\fP"
.br
.ti -1c
.RI "typedef struct SimplexInfo \fBSimplexInfo\fP"
.br
.ti -1c
.RI "typedef struct SimAnn \fBSimAnn\fP"
.br
.ti -1c
.RI "typedef struct Threadpool \fBThreadpool\fP"
.br
.ti -1c
.RI "typedef struct ThreadQueue \fBThreadQueue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Typedefs of all classes 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP


\fBAuthor:\fP
.RS 4
Alan R\&. Rogers 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
