.TH "vcf2gtp.py" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vcf2gtp.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBvcf2gtp\&.Map\fP"
.br
.RI "\fIRepresents the genetic map\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBvcf2gtp\&.usage\fP"
.br
.ti -1c
.RI "def \fBvcf2gtp\&.VCFparse\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBvcf2gtp\&.mapFname\fP = None"
.br
.ti -1c
.RI "\fBvcf2gtp\&.map\fP = None"
.br
.ti -1c
.RI "\fBvcf2gtp\&.vcfFile\fP = None"
.br
.ti -1c
.RI "float \fBvcf2gtp\&.recomb\fP = 0\&.0"
.br
.ti -1c
.RI "\fBvcf2gtp\&.extrapolate\fP = False"
.br
.ti -1c
.RI "int \fBvcf2gtp\&.i\fP = 1"
.br
.ti -1c
.RI "list \fBvcf2gtp\&.vcfFname\fP = sys\&.argv[i]"
.br
.ti -1c
.RI "tuple \fBvcf2gtp\&.line\fP = vcfFile\&.readline()"
.br
.ti -1c
.RI "int \fBvcf2gtp\&.snpid\fP = 0"
.br
.ti -1c
.RI "tuple \fBvcf2gtp\&.mappos\fP = map\&.getMapPos(nucpos0)"
.br
.ti -1c
.RI "string \fBvcf2gtp\&.msg\fP = 'ERR: vcf file contains multiple chromosomes: %s, %s\&.\\n'"
.br
.ti -1c
.RI "\fBvcf2gtp\&.nucpos0\fP = nucpos"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
