.TH "vcf2gtp" 3 "Thu May 29 2014" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vcf2gtp \- Convert \&.vcf files into \&.gtp format\&.
.PP
.SH "\fBvcf2gtp\&.py\fP, a program that converts \&.vcf files into \&.gtp format "
.PP
.PP
.PP
.nf
usage: vcf2gtp [options filename.vcf geneticMapFile]
where options may include:

  -r <x> or --recombPerBP <x>     Set recombination rate per nucleotide.

If two filenames are provided, the first must be a vcf file and the
second a file of recombination rates. In this case, the -r option is
not allowed.

If one filename is provided, it must be a vcf file, and the -r option
is mandatory.

If no filename is provided, the program reads vcf data from standard
input and the -r option is mandatory.

The program writes to standard output.
.fi
.PP
.PP
If no file is provided for recombination rates, the rate must be specified using the \fC-r\fP or \fC--recombPerBP\fP option, and the program generates map distances assuming that the recombination rate between two sites is proportional to the number of nucleotides that separate them\&.
.PP
The genetic map file must have a format like this: 
.PP
.nf
position COMBINED_rate(cM/Mb) Genetic_Map(cM)
14431347 9.6640973708 0
14432618 9.7078062447 0.0122830678
14433624 9.7138922111 0.0220491208
14433659 9.7163435060 0.0223891071
14433758 9.7078087850 0.0233510251

.fi
.PP
.PP
The first line is a list of column labels\&. After that, each row corresponds to a \fBSNP\fP\&. The first column gives the position, in nucleotides from the end of the chromosome\&. The second column gives the recombination rate, in cM per Mb, between that \fBSNP\fP and the next one, and the third column gives the map distance in cM\&. This is the format used by the 1000-Genomes Project
.PP
\fBAuthor:\fP
.RS 4
Ryan Bohlender and Alan Rogers 
.RE
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Ryan Bohlender and Alan R\&. Rogers rogers@anthro.utah.edu\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP

