.TH "window.h" 3 "Sat Jun 6 2015" "Version 0.1" "ldpsiz" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window.h \- 
.PP
Header for \fBwindow\&.c\fP 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP
 

.SH SYNOPSIS
.br
.PP
\fC#include 'snp\&.h'\fP
.br
\fC#include 'typedefs\&.h'\fP
.br
\fC#include 'boot\&.h'\fP
.br
\fC#include 'em\&.h'\fP
.br
\fC#include 'misc\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBWindow_advance\fP (\fBWindow\fP *window, \fBTabulation\fP *tab, \fBSpectab\fP *spectab, \fBBoot\fP *boot, long lineno)"
.br
.RI "\fIEstimate the linkage disequilibrium (LD) between single nucleotide polymorphisms (SNPs) as a function of the map distance between those SNPs\&. \fP"
.ti -1c
.RI "\fBSNP\fP * \fBWindow_currSNP\fP (\fBWindow\fP *window)"
.br
.RI "\fIReturn pointer to current focal \fBSNP\fP\&. \fP"
.ti -1c
.RI "void \fBWindow_free\fP (\fBWindow\fP *window)"
.br
.RI "\fIFree a \fBWindow\fP\&. \fP"
.ti -1c
.RI "int \fBWindow_nextSNP\fP (\fBWindow\fP *window, \fBBoot\fP *boot)"
.br
.RI "\fIGet next \fBSNP\fP from input file and link it into the linked list pointed to by window->curr\&. \fP"
.ti -1c
.RI "\fBWindow\fP * \fBWindow_new\fP (double width_cm, FILE *ifp, long sampling_interval, unsigned ploidy)"
.br
.ti -1c
.RI "unsigned \fBWindow_nGtype\fP (const \fBWindow\fP *window)"
.br
.RI "\fIReturn current value of window->nGtype\&. \fP"
.ti -1c
.RI "unsigned \fBWindow_ploidy\fP (const \fBWindow\fP *window)"
.br
.RI "\fIReturn window->ploidy\&. \fP"
.ti -1c
.RI "long \fBWindow_nSNPsRead\fP (const \fBWindow\fP *window)"
.br
.RI "\fIReturn the number of SNPs that have been read\&. \fP"
.ti -1c
.RI "void \fBWindow_test\fP (int verbose)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header for \fBwindow\&.c\fP 
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP


\fBAuthor:\fP
.RS 4
Alan R\&. Rogers 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int \fBWindow_advance\fP (\fBWindow\fP *window, \fBTabulation\fP *tab, \fBSpectab\fP *spectab, \fBBoot\fP *boot, longlineno)"
.PP
Estimate the linkage disequilibrium (LD) between single nucleotide polymorphisms (SNPs) as a function of the map distance between those SNPs\&. Definition is provided openly here (rather than hidden in \fBwindow\&.c\fP) so that functions can be inlined\&.
.PP
\fBCopyright:\fP
.RS 4
Copyright (c) 2014, Alan R\&. Rogers <rogers@anthro.utah.edu>\&. This file is released under the Internet Systems Consortium License, which can be found in file 'LICENSE'\&. 
.RE
.PP

.PP
References Boot_addAlleleCount(), Window::curr, Dbl_near(), Window::ploidy, Window::sampling_interval, SNP_countMinor(), SNP_getDsq(), SNPstore_checkin(), Window::store, Window::width_cm, and Window_nextSNP()\&.
.SS "int \fBWindow_nextSNP\fP (\fBWindow\fP *window, \fBBoot\fP *boot)"
.PP
Get next \fBSNP\fP from input file and link it into the linked list pointed to by window->curr\&. Return 0 on success, EOF if end of file is reached, and 1 on any other error\&. 
.PP
References Window::curr, Dbl_near(), Gtp_readSNP(), Window::gtype, Window::ifp, Window::nGtype, Window::nSNPs, Window::ploidy, SNP_set(), SNP_show(), SNPstore_checkout(), SNPstore_new(), and Window::store\&.
.PP
Referenced by threadfun(), and Window_advance()\&.
.SS "long \fBWindow_nSNPsRead\fP (const \fBWindow\fP *window)"
.PP
Return the number of SNPs that have been read\&. 
.PP
References Window::nSNPs\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for ldpsiz from the source code\&.
