ldpsiz: assign.h File Reference
assign.h File Reference
Header for functions defined in assign.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include "typedefs.h"
#include <stdio.h>
Defines
#define MANDATORY 1
Functions
Assignment * Assignment_new (Assignment *a, const char *key, const char *value)
Insert new assignment.
void Assignment_free (Assignment *a)
Free list of Assignment objects.
const char * Assignment_value (const Assignment *a, const char *key)
Return value corresponding with given key, or NULL if no such key is found.
void Assignment_print (const Assignment *a, FILE *fp)
int Assignment_setDbl (const Assignment *a, const char *key, double *ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
int Assignment_setLong (const Assignment *a, const char *key, long *ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
int Assignment_setInt (const Assignment *a, const char *key, int *ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
unsigned Assignment_setUnsignedInt (const Assignment *a, const char *key, unsigned *ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
int Assignment_setString (const Assignment *a, const char *key, char *ptr, int size, int mandatory)
Initialize *ptr do value corresponding to given key.
Assignment * Assignment_readEld (FILE *ifp)
Read assignment statements in file produced by eld.
Detailed Description
Header for functions defined in assign.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Function Documentation
void Assignment_free (Assignment * head)
Free list of Assignment objects.
References Assignment_free(), Assignment::key, Assignment::next, and Assignment::value.
Referenced by Assignment_free(), FileIndex_readFile(), and Ini_free().
Assignment* Assignment_new (Assignment * head, const char * key, const char * value)
Insert new assignment.
References Assignment_new(), Assignment::key, Assignment::next, and Assignment::value.
Referenced by Assignment_new(), Assignment_readEld(), Gtp_readHdr(), and Ini_new().
Assignment* Assignment_readEld (FILE * ifp)
Read assignment statements in file produced by eld.
Parameters:
[in] ifp Pointer to input file.
Returns:
Pointer to an Assignment object, which contains all the assignments found.
References Assignment_new().
int Assignment_setDbl (const Assignment * a, const char * key, double * ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters:
[in] a A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts if "key" is not found.
[out] ptr Points to a double variable, which will be initialized. If variable "key" has been assigned, then its value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns:
1 if variable was initialized, 0 otherwise.
References Assignment_value(), and Assignment::value.
Referenced by Ini_setDbl().
int Assignment_setInt (const Assignment * a, const char * key, int * ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters:
[in] a A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts if "key" is not found.
[out] ptr Points to a variable of type "int", which will be initialized. If variable "key" has been assigned, then its value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns:
1 if variable was initialized, 0 otherwise.
References Assignment_value(), and Assignment::value.
Referenced by FileIndex_readFile(), and Ini_setInt().
int Assignment_setLong (const Assignment * a, const char * key, long * ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters:
[in] a A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts if "key" is not found.
[out] ptr Points to a variable of type "long int", which will be initialized. If variable "key" has been assigned, then its value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns:
1 if variable was initialized, 0 otherwise.
References Assignment_value(), and Assignment::value.
Referenced by Ini_setLong().
int Assignment_setString (const Assignment * a, const char * key, char * ptr, int size, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters:
[in] a A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts if "key" is not found.
[out] ptr Points to a character array containing "size" bytes. If the variable "key" has been assigned, its value will be copied into "ptr". Otherwise, *ptr is unaltered.
Returns:
1 if variable was initialized, 0 otherwise.
References Assignment_value(), and Assignment::value.
Referenced by Ini_setString().
unsigned Assignment_setUnsignedInt (const Assignment * a, const char * key, unsigned * ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters:
[in] a A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts if "key" is not found.
[out] ptr Points to a variable of type "unsigned int", which will be initialized. If variable "key" has been assigned, then its value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns:
1 if variable was initialized, 0 otherwise.
References Assignment_value(), and Assignment::value.
Referenced by Ini_setUnsignedInt().