ldpsiz: boot.c File Reference
boot.c File Reference
Functions for a moving blocks bootstrap.
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <assert.h>
#include <gsl/gsl_rng.h>
#include "tabulation.h"
#include "misc.h"
#include "window.h"
#include "boot.h"
Data Structures
struct Boot
Contains the all data involved in a moving blocks bootstrap.
struct BootConf
Contains the data for a bootstrap confidence interval.
Functions
static void Boot_allocArrays (Boot *boot)
Allocate Boot's arrays.
Boot * Boot_new (long nSNPs, long nReps, long blockLength, double windowcm, int nBins, gsl_rng *rng)
Constructor for class Boot.
long Boot_multiplicity (const Boot *boot, long snp, long rep)
void Boot_addLD (Boot *boot, double Dsq, double pqpq, double sep_cm, const SNP *snp1, const SNP *snp2)
Boot * Boot_dup (const Boot *old)
long Boot_nReps (const Boot *boot)
int Boot_nBins (const Boot *boot)
long Boot_nBlocks (const Boot *boot)
Return number of blocks.
long Boot_nSNPs (const Boot *boot)
Return number of SNPs.
void Boot_free (Boot *boot)
double interpolate (double p, double *v, long len)
Interpolate in order to approximate the value v[p*(len-1)].
int Boot_equals (const Boot *x, const Boot *y)
void Boot_plus_equals (Boot *x, const Boot *y)
void Boot_dump (const Boot *boot, FILE *ofp)
Boot * Boot_restore (FILE *ifp)
void Boot_get_rep (Boot *boot, double *sigdsq, double *rsq, double *cm, long unsigned *nobs, int rep)
Fill arrays sigdsq, cm, and nobs with values for bootstrap repetition "rep".
long unsigned Boot_rawCounts (const Boot *boot, int rep, int bin, double *numerator, double *denominator, double *sumRsq, double *sep_cm)
long Boot_purge (Boot *boot)
Remove replicates in which some bins have zero observations.
void Boot_print (const Boot *boot, FILE *ofp)
Print a Boot object.
long Boot_multiplicity_slow (Boot *boot, long snp, long rep)
BootConf * BootConf_new (Boot *boot, double confidence)
void confidenceBounds (double *lowBnd, double *highBnd, double confidence, double *v, long len)
Calculate confidence bounds from a vector of values representing samples drawn from the sampling distribution of some estimator.
void BootConf_printHdr (const BootConf *bc, FILE *ofp)
double BootConf_lowBound (const BootConf *bc, long bin)
double BootConf_highBound (const BootConf *bc, long bin)
void BootConf_print (const BootConf *bc, FILE *ofp)
void BootConf_free (BootConf *bc)
Detailed Description
Functions for a moving blocks bootstrap.
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Function Documentation
static void Boot_allocArrays (Boot * boot) [static]
Allocate Boot's arrays.
This code is used in several places, and I have it here to ensure consistency.
References Boot::nBlocks, Boot::nReps, Boot::start, and Boot::tab.
Referenced by Boot_new().
void Boot_get_rep (Boot * boot, double * sigdsq, double * rsq, double * cm, long unsigned * nobs, int rep)
Fill arrays sigdsq, cm, and nobs with values for bootstrap repetition "rep".
If nobs==NULL, nothing is stored there.
References Boot::tab.
long Boot_purge (Boot * boot)
Remove replicates in which some bins have zero observations.
These would generate NaN values in the calculation of sigdsq, which are not handled by the minimizer. Return revised number of bootstrap replicates.
References Boot::nBins, Boot::nReps, Boot::start, and Boot::tab.
void confidenceBounds (double * lowBnd, double * highBnd, double confidence, double * v, long len)
Calculate confidence bounds from a vector of values representing samples drawn from the sampling distribution of some estimator.
To calculate the lower bound (*lowBnd), the function calculates the total probability mass in the tails (1 - confidence) and divides this into two equal parts to find p, the probability mass in each tail. It then estimates a value L such that a fraction p of the data values are less than or equal to L. To find this value, the function uses linear interpolation between the sorted list of data values.
The upper bound (*highBnd) is calculated in an analogous fashion.
Parameters:
[out] lowBnd,highBnd Calculated results will be written into these memory locations.
[in] confidence Fraction of sampling distribution that lies inside the confidence bounds.
[in] v The vector of values.
[in] len The number of values inf v.
Side Effects:
The function sorts the vector v.
References compareDoubles(), and interpolate().
double interpolate (double p, double * v, long len)
Interpolate in order to approximate the value v[p*(len-1)].
Return NaN if len==0.
Referenced by confidenceBounds().