ldpsiz: boot.h File Reference
boot.h File Reference
Header for boot.c.
#include <gsl/gsl_rng.h>
#include "typedefs.h"
Functions
void confidenceBounds (double *lowBnd, double *highBnd, double confidence, double *v, long len)
Calculate confidence bounds from a vector of values representing samples drawn from the sampling distribution of some estimator.
double interpolate (double p, double *v, long len)
Interpolate in order to approximate the value v[p*(len-1)].
Boot * Boot_new (long nSNPs, long nReps, long blockLength, double windowcm, int nBins, gsl_rng *rng)
Constructor for class Boot.
void Boot_addLD (Boot *boot, double Dsq, double pqpq, double sep_cm, const SNP *snp1, const SNP *snp2)
void Boot_free (Boot *boot)
int Boot_equals (const Boot *x, const Boot *y)
Boot * Boot_dup (const Boot *old)
long Boot_nReps (const Boot *boot)
int Boot_nBins (const Boot *boot)
long Boot_nBlocks (const Boot *boot)
Return number of blocks.
long Boot_nSNPs (const Boot *boot)
Return number of SNPs.
void Boot_plus_equals (Boot *x, const Boot *y)
void Boot_dump (const Boot *boot, FILE *ofp)
Boot * Boot_restore (FILE *ifp)
long Boot_multiplicity (const Boot *boot, long ndx, long rep)
void Boot_get_rep (Boot *boot, double *sigdsq, double *rsq, double *cm, long unsigned *nobs, int rep)
Fill arrays sigdsq, cm, and nobs with values for bootstrap repetition "rep".
long unsigned Boot_rawCounts (const Boot *boot, int rep, int bin, double *numerator, double *denominator, double *sumRsq, double *sep_cm)
long Boot_purge (Boot *boot)
Remove replicates in which some bins have zero observations.
void Boot_print (const Boot *boot, FILE *ofp)
Print a Boot object.
long Boot_multiplicity_slow (Boot *boot, long snp, long rep)
BootConf * BootConf_new (Boot *boot, double confidence)
void BootConf_printHdr (const BootConf *bc, FILE *ofp)
double BootConf_lowBound (const BootConf *bc, long bin)
double BootConf_highBound (const BootConf *bc, long bin)
void BootConf_print (const BootConf *bc, FILE *ofp)
void BootConf_free (BootConf *bc)
Detailed Description
Header for boot.c.
Author
Alan R. Rogers
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
void Boot_get_rep (Boot * boot, double * sigdsq, double * rsq, double * cm, long unsigned * nobs, int rep)
Fill arrays sigdsq, cm, and nobs with values for bootstrap repetition "rep".
If nobs==NULL, nothing is stored there.
References Boot::tab.
long Boot_purge (Boot * boot)
Remove replicates in which some bins have zero observations.
These would generate NaN values in the calculation of sigdsq, which are not handled by the minimizer. Return revised number of bootstrap replicates.
References Boot::nBins, Boot::nReps, Boot::start, Boot::tab, Tabulation_nObs(), and Tabulation_overflow().
void confidenceBounds (double * lowBnd, double * highBnd, double confidence, double * v, long len)
Calculate confidence bounds from a vector of values representing samples drawn from the sampling distribution of some estimator.
To calculate the lower bound (*lowBnd), the function calculates the total probability mass in the tails (1 - confidence) and divides this into two equal parts to find p, the probability mass in each tail. It then estimates a value L such that a fraction p of the data values are less than or equal to L. To find this value, the function uses linear interpolation between the sorted list of data values.
The upper bound (*highBnd) is calculated in an analogous fashion.
Parameters
[out] lowBnd,highBnd Calculated results will be written into these memory locations.
[in] confidence Fraction of sampling distribution that lies inside the confidence bounds.
[in] v The vector of values.
[in] len The number of values inf v.
Side Effects:
The function sorts the vector v.
References compareDoubles(), and interpolate().
double interpolate (double p, double * v, long len)
Interpolate in order to approximate the value v[p*(len-1)].
Return NaN if len==0.
Referenced by confidenceBounds().