ldpsiz: chain.c File Reference
chain.c File Reference
A linked list of Markov chains, used in Markov-coupled Markov chain Monte Carlo (MCMCMC).
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include <math.h>
#include <float.h>
#include <limits.h>
#include <time.h>
#include <string.h>
#include <pthread.h>
#include <gsl/gsl_rng.h>
#include "pophist.h"
#include "model.h"
#include "chain.h"
#include "misc.h"
Data Structures
struct ChainState
The state of a single Markov chain.
struct Chain
A linked list of Markov chains, which differ in the extent to which the objective function has been artificially flattened.
Functions
ChainState * ChainState_new (PopHist *ph)
Allocate and initialize a new ChainState structure.
void ChainState_free (ChainState *cs)
De-allocate a ChainState object.
void Chain_publish (Chain *chain)
Make data available to other threads.
Chain * Chain_next (Chain *chain)
Return pointer to next Chain in linked list.
unsigned Chain_naccepted (Chain *chain)
Number of proposals accepted so far by this chain.
unsigned Chain_nswapped (Chain *chain)
Number of times this chain has swapped states with the next.
unsigned Chain_which (Chain *chain)
Return the index of this chain.
Chain * Chain_new (unsigned which, unsigned nChains, unsigned nreps, double u, double dt, double dNinv, double temp, unsigned nbins, double *sigdsq, double *c, PopHist *ph, Model *model, double odeAbsTol, double odeRelTol, unsigned swapInterval)
Allocate memory for a Chain.
void Chain_sanityCheck (Chain *chain, const char *file, int line)
void Chain_free (Chain *chain)
Free memory allocated by linked list of chains.
void Chain_prStateAddr (const Chain *chain, int ndx, const char *file, int line)
Print machine address of state of each chain in linked list.
int Chain_accepted (const Chain *c)
Return 1 if chain's state changed; 0 otherwise.
void Chain_swapState (Chain *c)
Swap states of chains c and c->next.
void Chain_waitForData (Chain *chain)
Wait until thread has completed another iteration and made the resulting data available.
void Chain_waitUntilDataNeeded (Chain *chain)
Wait until main thread has finished with data from last iteration.
void Chain_setDataAvailable (Chain *chain)
Indicate that data are available.
void Chain_setDataNeeded (Chain *chain)
Indicate that data are needed.
void Chain_signal (Chain *chain)
Send signal via condition variable.
void Chain_lock (Chain *chain)
Lock chain.
void Chain_unlock (Chain *chain)
Unlock chain.
void Chain_lockStdout (void)
Lock stdout.
void Chain_unlockStdout (void)
Unock stdout.
double Chain_lnObj (Chain *chain)
Log of objective function.
double Chain_flatness (Chain *chain)
Return flatness parameter of chain.
void Chain_printFull (Chain *chain, FILE *fp)
Print entire chain.
void Chain_bestFit (Chain *chain, double *bestLnObj, PopHist *bestPh)
Return values corresponding to the best fit.
void * runChain (void *arg)
void Chain_printHdr (Chain *chain, FILE *fp)
Printer header for markov chain output lines.
void Chain_printState (Chain *chain, FILE *fp)
Printer state of markov chain.
Variables
pthread_mutex_t stdout_mutex = PTHREAD_MUTEX_INITIALIZER
Detailed Description
A linked list of Markov chains, used in Markov-coupled Markov chain Monte Carlo (MCMCMC).
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Function Documentation
void Chain_bestFit (Chain * chain, double * bestLnObj, PopHist * bestPh)
Return values corresponding to the best fit.
Parameters:
[out] bestLnObj Pointer to double, into which the function will write the value of the log objective function.
[out] ph Pointer to a PopHist, into which the optimal population history will be written.
References PopHist_copy().
double Chain_flatness (Chain * chain)
Return flatness parameter of chain.
References Chain::flatness.
double Chain_lnObj (Chain * chain)
Log of objective function.
Does not calculate function. Just returns current stored value.
Referenced by Chain_printState().
void Chain_setDataAvailable (Chain * chain)
Indicate that data are available.
Chain should be locked before calling this function.
Referenced by Chain_publish().
void Chain_setDataNeeded (Chain * chain)
Indicate that data are needed.
Chain should be locked before calling this function.
void Chain_swapState (Chain * c)
Swap states of chains c and c->next.
Lock both chains before calling this function.
References Chain::next.
void Chain_waitForData (Chain * chain)
Wait until thread has completed another iteration and made the resulting data available.
On return, chain will be locked.
void Chain_waitUntilDataNeeded (Chain * chain)
Wait until main thread has finished with data from last iteration.
On return, the chain will be locked.
ChainState * ChainState_new (PopHist * ph)
Allocate and initialize a new ChainState structure.
Occupies a single block of memory, using the "struct hack" of C programming.
References ChainState::ph, PopHist_calcSize(), PopHist_copy(), PopHist_init(), and PopHist_nepoch().
Referenced by Chain_new().