ldpsiz: eld.c File Reference
eld.c File Reference
Estimate LD from genetic data.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <math.h>
#include <time.h>
#include <assert.h>
#include <getopt.h>
#include <limits.h>
#include <pthread.h>
#include <gsl/gsl_rng.h>
#include "typedefs.h"
#include "misc.h"
#include "readgtp.h"
#include "fileindex.h"
#include "tabulation.h"
#include "window.h"
#include "boot.h"
#include "assign.h"
#include "ini.h"
Data Structures
struct ThreadArg
Data required by a single thread.
Functions
static void usage (void)
Print usage message and abort.
void ThreadArg_print (ThreadArg *targ, FILE *ofp)
Print ThreadArg object.
void * threadfun (void *varg)
eld runs a copy of this function within each thread.
int main (int argc, char **argv)
Detailed Description
Estimate LD from genetic data.
eld, a program that estimates LD from genetic data
Parameter values, including those describing population history, may be read either from the initialization file ldpsiz.ini or specified on the command line. Command-line arguments override values in the initialization file.
eld reads data in "gtp" format and estimates two measures of LD: and . The program compares all pairs of sites within a window that slides across the data set. These pairs are tabulated into bins based on the distance (in cM) that separates them. For each bin, the program estimates and prints the two measures of LD. The maximal separation between pairs of SNPs is determined by the --window (or -w) option.
Optionally, the program calculates a moving-blocks bootstrap for . To turn on this option, use the --bootreps option discussed below. The program will then print lower and upper confidence limits along with each estimate of . By default, the bootstrap includes 95% of the sampling distribution distribution. This fraction can be modified using the initialization file. Optionally, the bootstrap may be stored in a separate file for use by other programs. To accomplish this, use the command-line option --bootfile or set bootfile in ldpsiz.ini.
By default, the program uses as many threads as there are cores on the machine. To change this, use the command-line option --threads or set nthreads in the file ldpsiz.ini.
usage: eld [options] input_file_name
   where options may include:
   -b \<x\> or --blocksize \<x\>
      SNPs per bootstrap block
   -f \<x\> or --bootfile \<x\>
      name of bootstrap output file
   -h or --help
      print this message
   -i \<x\> or --interval \<x\>
      for debugging: increase speed by examining every x'th focal SNP
   -n \<x\> or --nbins \<x\>
      tablulate values into x bins
   -r \<x\> or --bootreps \<x\>
      number of bootstrap replicates (def: 0)
   -t \<x\> or --threads \<x\>
      number of threads (default is auto)
   -v     or --verbose
      more output
   -w \<x\> or --window \<x\>
      window size in cM
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
void * threadfun (void * vjq)
eld runs a copy of this function within each thread.
Waits until there is a job in the queue, pops it off and executes it, then waits for another.
The function opens the input file, which gives the thread its own input buffer so that it can move around in the file without locking it. Then it examines pairs of SNPs within a window that slides across the SNPs it is responsible for, placing the results into an object of type Tabulation.
Parameters
varg A void pointer to an object of type ThreadArg.
Runs until jobs are completed and main thread sets acceptingJobs=0.
References ThreadArg::boot, ThreadArg::ifname, ThreadArg::nGtype, ThreadArg::overflow, ThreadArg::ploidy, ThreadArg::sampling_interval, ThreadArg::tab, Tabulation_overflow(), ThreadArg::tb, ThreadBounds_ndx_1stFocal(), ThreadBounds_ndx_initial(), ThreadBounds_ndx_lastFocal(), ThreadBounds_seekpos_initial(), Window_advance(), ThreadArg::window_cm, Window_free(), Window_new(), Window_nextSNP(), and Window_nGtype().