ldpsiz: em.h File Reference
em.h File Reference
Header for em.c.
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include <stdio.h>
#include <assert.h>
#include "typedefs.h"
#include "window.h"
Data Structures
struct DsqData
Data used by EM algorithm in estimating Dsq from partially phased diploid data.
Defines
#define HOMOZYGOTE(A) ((A)==0 || (A)==3)
Is A a homozygote?
#define UNPHASED_PAIR(A, B)
True if A and B are both heterozygotes and at least one is unphased.
#define MAKE_PHASED(A) ((A)==UNPHASED_HETEROZYGOTE ? 1 : (A))
If A is an unphased heterozygote, then convert it to a phased one (genotype 1).
Functions
void DsqData_print (DsqData *dd, const char *file, int line, FILE *fp)
Print an object of type DsqData.
void DsqData_reset (DsqData *dd)
Make DsqData object consistent with its current allele freqs.
double loD (double pA, double pB, unsigned *nGam)
Lowest feasible value of D, given allele frequencies.
double hiD (double pA, double pB, unsigned *nGam)
Highest feasible value of D, given allele frequencies.
int minimize1D (double *D, DsqData *dd)
This algorithm finds the minimum of function negLnL within the range [a,b], where a = dd->loD, and b=dd->hiD.
static void trBits (unsigned char *x, unsigned char *y)
Think of x and y as the two rows of a matrix, with the columns of the matrix equal to the bits of x and y.
static unsigned char gamete (unsigned char x, unsigned char y)
Detailed Description
Header for em.c.
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Define Documentation
#define MAKE_PHASED (A) ((A)==UNPHASED_HETEROZYGOTE ? 1 : (A))
If A is an unphased heterozygote, then convert it to a phased one (genotype 1).
Otherwise leave it alone.
Referenced by SNP_getDsq().
#define UNPHASED_PAIR (A, B)
Value:
(((A)==UNPHASED_HETEROZYGOTE && !HOMOZYGOTE(B)) \
                            || ((B)==UNPHASED_HETEROZYGOTE && !HOMOZYGOTE(A)))
True if A and B are both heterozygotes and at least one is unphased.
Referenced by SNP_getDsq().
Function Documentation
void DsqData_reset (DsqData * dd)
Make DsqData object consistent with its current allele freqs.
References DsqData::alpha, DsqData::beta, DsqData::hiD, hiD(), DsqData::loD, loD(), DsqData::nGam, DsqData::px, and DsqData::py.
int minimize1D (double * D, DsqData * dd)
This algorithm finds the minimum of function negLnL within the range [a,b], where a = dd->loD, and b=dd->hiD.
The algorithm uses Newton steps when these go downhill, and otherwise bisects in the downhill direction.
When Newton fails, the next step is in the downhill direction, as indicated by the derivative. If the derivative at the boundary has the same sign as that at the current point, the algorithm bets that the function is monotonic and takes a big step. Otherwise, there must be an intermediate minimum, so the algorithm bisects.
Parameters:
[out] D Lewontin's original measure of linkage disequilibrium,
[in] dd pointer to object of type DsqData
Returns:
the integer 0
References DsqData::hiD, initialD(), DsqData::loD, negLnL_df(), negLnL_df12(), and DsqData::tol.
Referenced by SNP_getDsq().
static void trBits (unsigned char * x, unsigned char * y) [inline, static]
Think of x and y as the two rows of a matrix, with the columns of the matrix equal to the bits of x and y.
We are only interested in the low-order (rightmost) pair of bits. Transpose that 2X2 matrix, so that x and y are set equal to the bits that had previously been in the columns.
In other words, if [i,j] are the right-most two bits of x, and [k,l] are the right-most two bits of y, then the function does the following transformation:
x: i j x: i k ----> y: k l y: j l
Suppose, for example, that x=2, or in binary, x=0b10. Furthermore, suppose that y=3=0b11. Then after a call to trBits, we'll have x=3=0b11 and y=1=0b01.
Any higher-order bits are ignored. For example, the preceding example still generates x=3 and y=1, even if on input y=7=0b111.
Referenced by SNP_getDsq().