ldpsiz: em.c File Reference
em.c File Reference
Estimate D from partially phased diploid data using the EM algorithm.
#include <stdio.h>
#include <math.h>
#include <float.h>
#include <assert.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_min.h>
#include "em.h"
#include "misc.h"
Macros
#define GO_RIGHT(F, A, X, B) ((X) + (F)*((B)-(X)))
#define GO_LEFT(F, A, X, B) ((X) - (F)*((X)-(A)))
Functions
double negLnL (double D, void *data)
Negative of log Likelihood of given value of D.
double negLnL_df (double D, void *data)
Negative of log Likelihood of given value of D.
void negLnL_fdf (double D, double *f, double *df, void *data)
Negative of log Likelihood of given value of D.
void negLnL_fddf (double D, double *f, double *df, double *ddf, void *data)
Negative of log Likelihood of given value of D.
void negLnL_df12 (double D, double *df, double *ddf, void *data)
Negative of log Likelihood of given value of D.
static double get_w (double D, DsqData *dd)
Return value of w implied by D, and the parameters in d.
static double getD (double w, DsqData *dd)
Return value of D implied by given value of w.
static double next_w (double w, DsqData *dd)
One step of EM algorithm.
double find_D (double D0, DsqData *dd)
Ad hoc iterations to find D.
static double initialD (DsqData *dd)
Initialize DsqData object from current data, assuming that half of unphased heterozygotes have 2-locus genotype 11/00 and the other half have 10/01.
void DsqData_print (DsqData *dd, const char *file, int line, FILE *fp)
Print an object of type DsqData.
void DsqData_reset (DsqData *dd)
Make DsqData object consistent with its current allele freqs.
double loD (double pA, double pB, unsigned *nGam)
Lowest feasible value of D, given allele frequencies.
double hiD (double pA, double pB, unsigned *nGam)
Highest feasible value of D, given allele frequencies.
int minimize1D (double *D, DsqData *dd)
This algorithm finds the minimum of function negLnL within the range [a,b], where a = dd->loD, and b=dd->hiD.
Detailed Description
Estimate D from partially phased diploid data using the EM algorithm.
Author
Alan R. Rogers
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
void DsqData_reset (DsqData * dd)
Make DsqData object consistent with its current allele freqs.
References DsqData::alpha, DsqData::beta, DsqData::hiD, hiD(), DsqData::loD, loD(), DsqData::nGam, DsqData::px, and DsqData::py.
double find_D (double D0, DsqData * dd)
Ad hoc iterations to find D.
Parameters
[in] D0 Starting value for EM algorithm.
[in] d Points to a structure containing data.
References get_w(), getD(), and DsqData::tol.
static double getD (double w, DsqData * dd) inline static
Return value of D implied by given value of w.
Parameters
[in] w Current guess as to fraction of unphased double-heterozygotes with two-locus genotype 11/00 rather than 10/01.
[in] dd pointer to object of type DsqData
Returns
improved estimate of w
References DsqData::nGam, DsqData::nGtype, DsqData::nUnphased, DsqData::px, and DsqData::py.
Referenced by find_D(), and next_w().
int minimize1D (double * D, DsqData * dd)
This algorithm finds the minimum of function negLnL within the range [a,b], where a = dd->loD, and b=dd->hiD.
The algorithm uses Newton steps when these go downhill, and otherwise bisects in the downhill direction.
When Newton fails, the next step is in the downhill direction, as indicated by the derivative. If the derivative at the boundary has the same sign as that at the current point, the algorithm bets that the function is monotonic and takes a big step. Otherwise, there must be an intermediate minimum, so the algorithm bisects.
Parameters
[out] D Lewontin's original measure of linkage disequilibrium,
[in] dd pointer to object of type DsqData
Returns
the integer 0
References DsqData::hiD, initialD(), DsqData::loD, negLnL_df(), negLnL_df12(), and DsqData::tol.
Referenced by SNP_getDsq().
double negLnL_df (double D, void * data)
Negative of log Likelihood of given value of D.
This version returns only the 1st derivative.
References get_w(), DsqData::nGam, DsqData::nUnphased, DsqData::px, and DsqData::py.
Referenced by minimize1D().
void negLnL_df12 (double D, double * df, double * ddf, void * data)
Negative of log Likelihood of given value of D.
This version calculates the 1st derivative (placed in *df), and the 2nd derivative (in ddf).
References get_w(), DsqData::nGam, DsqData::nUnphased, DsqData::px, and DsqData::py.
Referenced by minimize1D().
void negLnL_fddf (double D, double * f, double * df, double * ddf, void * data)
Negative of log Likelihood of given value of D.
This version calculates, the function value (placed in *f), its 1st derivative (placed in *df), and its 2nd derivative (in ddf).
References get_w(), DsqData::nGam, DsqData::nUnphased, DsqData::px, and DsqData::py.
void negLnL_fdf (double D, double * f, double * df, void * data)
Negative of log Likelihood of given value of D.
This version calculates both the function value (placed in *f) and its derivative (placed in *df).
References get_w(), DsqData::nGam, DsqData::nUnphased, DsqData::px, and DsqData::py.
static double next_w (double w, DsqData * dd) inline static
One step of EM algorithm.
Parameters
[in] w Current guess as to fraction of unphased double-heterozygotes with two-locus genotype 11/00 rather than 10/01.
[in] dd pointer to object of type DsqData
Returns
improved estimate of w
References get_w(), and getD().