ldpsiz: fileindex.h File Reference
fileindex.h File Reference
Header for fileindex.c.
#include <stdio.h>
#include "typedefs.h"
Data Structures
struct ThreadBounds
Each ThreadBounds object contains the information needed by an individual thread to figure out where in the input file to begin reading SNPs and which SNP is its first focal SNP.
Functions
FileIndex * FileIndex_new (void)
Construct an empty FileIndex.
void FileIndex_free (FileIndex *fndx)
Free a FileIndex object.
long FileIndex_push (FileIndex *fndx, long seekpos, double mappos)
Record location data for a SNP in the FileIndex.
SNPLoc * FileIndex_atNdx (FileIndex *fndx, long ndx)
Return the SNPLoc object for SNP with given index.
long FileIndex_atMapPos (FileIndex *fndx, double mappos)
Return index of smallest element in sorted array that is >= mappos.
long FileIndex_nSNPs (FileIndex *fndx)
Return the number of SNPs.
void FileIndex_printSummary (FileIndex *fndx, FILE *ofp)
void FileIndex_printChunks (FileIndex *fndx, FILE *ofp)
void FileIndex_print (FileIndex *fndx, FILE *ofp)
FileIndex * FileIndex_readFile (FILE *ifp)
Read through a file, storing the location of each SNP in a structure of type FileIndex, which is then returned.
void FileIndex_realloc (FileIndex *fndx, long ptrsNeeded)
Reallocate the list of pointers so that the number of them is at least as large as ptrsNeeded.
double FileIndex_getMapPos (FileIndex *fndx, long ndx)
Return the map position (in cM) of SNP with given index.
long FileIndex_getSeekPos (FileIndex *fndx, long ndx)
Return the seek position of SNP with given index.
void FileIndex_sanityCheck (FileIndex *fi, const char *file, int lineno)
unsigned FileIndex_nPtrs (void)
unsigned FileIndex_chunkSize (void)
long FileIndex_nPtrsAllocated (const FileIndex *fndx)
long SNPLoc_seekpos (const SNPLoc *sl)
double SNPLoc_mappos (const SNPLoc *sl)
ThreadBounds * ThreadBounds_new (int nthreads, double windowcm, FileIndex *fndx)
Divide the genome into contiguous chunks of roughly equal size, so that each chunk can be processed by a separate thread.
void ThreadBounds_free (ThreadBounds *tb)
void ThreadBounds_print (const ThreadBounds *tb, int nthreads, FILE *ofp)
void ThreadBounds_sanityCheck (const ThreadBounds *tb, const char *file, int lineno)
void ThreadBounds_arraySanityCheck (const ThreadBounds *tb, int nthreads, const char *file, int lineno)
long ThreadBounds_ndx_initial (const ThreadBounds *tb)
Return the index of the starting SNP.
long ThreadBounds_ndx_1stFocal (const ThreadBounds *tb)
Return the index of the 1st focal SNP.
long ThreadBounds_ndx_lastFocal (const ThreadBounds *tb)
Return the index of the last focal SNP.
long ThreadBounds_seekpos_initial (const ThreadBounds *tb)
Return the seek position of the starting SNP.
long ThreadBounds_seekpos_1stFocal (const ThreadBounds *tb)
Return the seek position of the 1st focal SNP.
long ThreadBounds_seekpos_lastFocal (const ThreadBounds *tb)
Return the seek position of the last focal SNP.
double ThreadBounds_mappos_initial (const ThreadBounds *tb)
Return the map position of the starting SNP.
double ThreadBounds_mappos_1stFocal (const ThreadBounds *tb)
Return the map position of the 1st focal SNP.
double ThreadBounds_mappos_lastFocal (const ThreadBounds *tb)
Return the map position of the last focal SNP.
Detailed Description
Header for fileindex.c.
Author
Alan R. Rogers
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
SNPLoc* FileIndex_atNdx (FileIndex * fndx, long ndx)
Return the SNPLoc object for SNP with given index.
Referenced by FileIndex_atMapPos(), FileIndex_getMapPos(), and FileIndex_getSeekPos().
double FileIndex_getMapPos (FileIndex * fndx, long ndx)
Return the map position (in cM) of SNP with given index.
References FileIndex_atNdx().
Referenced by ThreadBounds_new().
long FileIndex_getSeekPos (FileIndex * fndx, long ndx)
Return the seek position of SNP with given index.
References FileIndex_atNdx().
Referenced by ThreadBounds_new().
long FileIndex_nSNPs (FileIndex * fndx)
Return the number of SNPs.
Referenced by FileIndex_atMapPos(), and ThreadBounds_new().
long FileIndex_push (FileIndex * fndx, long seekpos, double mappos)
Record location data for a SNP in the FileIndex.
Parameters
[in] fndx points to FileIndex.
[in] seekpos seek position of new entry
[in] mappos map position (in cM) of new entry
Returns
index of newly recorded SNP.
References FileIndex_realloc().
Referenced by FileIndex_readFile().
FileIndex* FileIndex_readFile (FILE * ifp)
Read through a file, storing the location of each SNP in a structure of type FileIndex, which is then returned.
Parameters
[in] ifp Pointer to input stream.
Returns
NULL if FILE pointer is NULL. If no sites are found, it returns an empty FileIndex. Otherwise, function returns a pointer to an object of type FileIndex.
References Assignment_free(), Assignment_setInt(), Dbl_near(), FileIndex_new(), FileIndex_push(), Gtp_readHdr(), and Gtp_readSNP().
void FileIndex_realloc (FileIndex * fndx, long ptrsNeeded)
Reallocate the list of pointers so that the number of them is at least as large as ptrsNeeded.
All newly-allocated pointers are set equal to NULL.
Referenced by FileIndex_push().
double ThreadBounds_mappos_1stFocal (const ThreadBounds * tb)
Return the map position of the 1st focal SNP.
double ThreadBounds_mappos_initial (const ThreadBounds * tb)
Return the map position of the starting SNP.
double ThreadBounds_mappos_lastFocal (const ThreadBounds * tb)
Return the map position of the last focal SNP.
long ThreadBounds_ndx_1stFocal (const ThreadBounds * tb)
Return the index of the 1st focal SNP.
Referenced by threadfun().
long ThreadBounds_ndx_initial (const ThreadBounds * tb)
Return the index of the starting SNP.
Referenced by threadfun().
long ThreadBounds_ndx_lastFocal (const ThreadBounds * tb)
Return the index of the last focal SNP.
Referenced by threadfun().
ThreadBounds* ThreadBounds_new (int nthreads, double windowcm, FileIndex * fndx)
Divide the genome into contiguous chunks of roughly equal size, so that each chunk can be processed by a separate thread.
On input, nthreads gives the number of threads, windowsize (the number of SNPs in the sliding window), and ifp points to the input file stream. The function returns a pointer to a newly-allocated array of type ThreadBounds, which has an entry for each thread, each of which is an object of type ThreadBounds. The i'th entry defines the starting position for thread i.
References FileIndex_atMapPos(), FileIndex_getMapPos(), FileIndex_getSeekPos(), and FileIndex_nSNPs().
long ThreadBounds_seekpos_1stFocal (const ThreadBounds * tb)
Return the seek position of the 1st focal SNP.
long ThreadBounds_seekpos_initial (const ThreadBounds * tb)
Return the seek position of the starting SNP.
Referenced by threadfun().
long ThreadBounds_seekpos_lastFocal (const ThreadBounds * tb)
Return the seek position of the last focal SNP.