ldpsiz: hill.h File Reference
hill.h File Reference
Header for hill.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include "typedefs.h"
#include "pophist.h"
Functions
void * HillData_new (void)
double HillData_stateVal (void *vdata, unsigned i)
i'th state value
void HillData_free (void *p)
free state variables
int Hill_geteq (double x[], double twoN, double c, double u)
int Hill_dydt (double t, const double y[], double f[], void *params)
params points to a structure of type dydt_params.
void Hill_approxeq (double x[], double twoN, double c, double u)
double Hill_sigdsq (ODE *ode, double c, double u, PopHist *ph, int twoNsmp)
Set state vector to initial equilibrium, then evolve it through the population history, and then use this state vector to calculate sigmdsq.
double Hill_sigdsqEq (double c, double u, PopHist *ph, unsigned whichEpoch, int twoNsmp, void *data)
Set state vector to equilibrium for Epoch "whichEpoch" and then use it to calculate sigmdsq.
size_t Hill_stateDim (void)
const char * Hill_stateLbl (unsigned i)
Model * Model_allocHill (int twoNsmp)
int Hill_evolveDiscrete (double y[], PopHist *ph, double c, double u)
Evolve through all Epochs of population history, using step size h and beginning with initial equilibrium.
double Hill_get_sigdsq (double y[], int twoNsmp)
Calculate sigma_d^2 from state vector.
int Hill_test_getDRM (double twoN, double c, double u)
int Hill_test_onestep (double *x1, int dim, double twoN, double c, double u)
int onestep_slow (const double x[], double y[], double twoN, double c, double u)
This version does not have unrolled loops.
Detailed Description
Header for hill.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Function Documentation
int Hill_dydt (double t_notused, const double x[], double f[], void * params)
params points to a structure of type dydt_params.
On return, f[] contains the derivatives of y1[], as approximated by difference equations.
References onestep().
Referenced by Hill_sigdsq().
int Hill_evolveDiscrete (double y[], PopHist * ph, double c, double u)
Evolve through all Epochs of population history, using step size h and beginning with initial equilibrium.
Calculation iterates Hill's difference equation. The initial value of y is set using Hill's equation for equilibrium.
Parameters:
[out] y On return, y contains Hill's vector of moments.
[in] ph Describes the population's history. If ph contains just one Epoch, y gets its equilibrium value.
[in] c Recombination rate; overrides values in ph.
[in] u Mutation rate.
Returns:
Always returns 0.
References iterate(), PopHist_duration(), PopHist_nepoch(), and PopHist_twoN().
double Hill_get_sigdsq (double y[], int twoNsmp)
Calculate sigma_d^2 from state vector.
On page 124, just after eqn 14, in Hill, William G. 1975. TPB 8:117-126.
References onestep().
Referenced by Hill_sigdsq(), and Hill_sigdsqEq().
int onestep_slow (const double x[], double y[], double twoN, double c, double u)
This version does not have unrolled loops.
Move the state vector forward one generation, using Hill's recurrence (Eqns 5 and 8).
Parameters:
input] x is the initial state vector.
output] y is the new state vector.