ldpsiz: hill.c File Reference
hill.c File Reference
Method of Hill, William G. 1975. TPB 8:117-126.
#include <math.h>
#include <string.h>
#include <gsl/gsl_matrix.h>
#include "misc.h"
#include "pophist.h"
#include "model.h"
#include "hill.h"
Data Structures
struct HillData
Macros
#define DIM 4
#define DPRINTF(arg)
Functions
static int onestep (const double x[], double y[], double twoN, double c, double u)
Move the state vector forward one generation, using Hill's recurrence (Eqns 5 and 8).
static int getDRM (double DRM[][DIM], double twoN, const double c, double u)
static int getDRM_slow (double DRM[][DIM], double twoN, const double c, double u)
int iterate (double y[], int t, double twoN, double c, double u)
Iterate the difference equation across t generations.
double Hill_exactLD (double c, double u, PopHist *ph, int twoNsmp, void *data)
void * HillData_new (void)
double HillData_stateVal (void *vdata, unsigned i)
i'th state value
void HillData_free (void *vdata)
free state variables
Model * Model_allocHill (int twoNsmp)
size_t Hill_stateDim (void)
const char * Hill_stateLbl (unsigned i)
int Hill_geteq (double x[], double twoN, double c, double u)
void Hill_approxeq (double x[], double twoN, double c, double u)
int Hill_dydt (double t_notused, const double x[], double f[], void *params)
params points to a structure of type dydt_params.
int Hill_test_getDRM (double twoN, double c, double u)
int Hill_test_onestep (double *x1, int dim, double twoN, double c, double u)
double Hill_sigdsqEq (double c, double u, PopHist *ph, unsigned whichEpoch, int twoNsmp, void *vdata)
Set state vector to equilibrium for Epoch "whichEpoch" and then use it to calculate sigmdsq.
double Hill_sigdsq (ODE *ode, double c, double u, PopHist *ph, int twoNsmp)
Set state vector to initial equilibrium, then evolve it through the population history, and then use this state vector to calculate sigmdsq.
double Hill_get_sigdsq (double y[], int twoNsmp)
Calculate sigma_d^2 from state vector.
int Hill_evolveDiscrete (double y[], PopHist *ph, double c, double u)
Evolve through all Epochs of population history, using step size h and beginning with initial equilibrium.
int onestep_slow (const double x[], double y[], double twoN, double c, double u)
This version does not have unrolled loops.
Variables
static const char * stateLbl [DIM]
Detailed Description
Method of Hill, William G. 1975. TPB 8:117-126.
Author
Alan R. Rogers The state variable is as defined on p 120 of Hill (1975). Hill's x corresponds to entries 0, 1, and 2 of my vector below. Hill also needs the expected heterozygosity (see his eqn 7), so I have added that on as element 3 of the state vector.
y[0] = E[H_A*H_B] y[1] = 4 E[sum_{ij} a_i b_j D_{ij}] y[2] = 2 E[sum_{ij} D_{ij}^2 y[3] = E[H_A] = E[H_B]
Here, a_i and b_j are the frequencies of the i'th allele at locus A and the j'th allele at locus B. D_{ij} is the coefficient of linkage disequilibrium between these alleles, H_A = 1 - sum a_i^2 is the heterozygosity at locus A and H_B is the corresponding value for locus B.
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
int Hill_dydt (double t_notused, const double x[], double f[], void * params)
params points to a structure of type dydt_params.
On return, f[] contains the derivatives of y1[], as approximated by difference equations.
References onestep().
Referenced by Hill_sigdsq().
int Hill_evolveDiscrete (double y[], PopHist * ph, double c, double u)
Evolve through all Epochs of population history, using step size h and beginning with initial equilibrium.
Calculation iterates Hill's difference equation. The initial value of y is set using Hill's equation for equilibrium.
Parameters
[out] y On return, y contains Hill's vector of moments.
[in] ph Describes the population's history. If ph contains just one Epoch, y gets its equilibrium value.
[in] c Recombination rate; overrides values in ph.
[in] u Mutation rate.
Returns
Always returns 0.
References iterate(), PopHist_duration(), PopHist_nepoch(), and PopHist_twoN().
double Hill_get_sigdsq (double y[], int twoNsmp)
Calculate sigma_d^2 from state vector.
On page 124, just after eqn 14, in Hill, William G. 1975. TPB 8:117-126.
References onestep().
Referenced by Hill_sigdsq(), and Hill_sigdsqEq().
static int iterate (double y[], int t, double twoN, double c, double u)
Iterate the difference equation across t generations.
References onestep().
Referenced by Hill_evolveDiscrete().
static int onestep (const double x[], double y[], double twoN, double c, double u) static
Move the state vector forward one generation, using Hill's recurrence (Eqns 5 and 8).
Parameters
input] x is the initial state vector.
output] y is the new state vector.
Referenced by Hill_dydt(), Hill_get_sigdsq(), and iterate().
int onestep_slow (const double x[], double y[], double twoN, double c, double u)
This version does not have unrolled loops.
Move the state vector forward one generation, using Hill's recurrence (Eqns 5 and 8).
Parameters
input] x is the initial state vector.
output] y is the new state vector.
Variable Documentation
const char* stateLbl[DIM] static
Initial value:
= { "Ha*Hb",
    "4S[abD]",
    "2S[D^2]",
    "H"
}