ldpsiz: ini.h File Reference
ini.h File Reference
Header for ini.c.
#include "typedefs.h"
#include <stdio.h>
Macros
#define MANDATORY 1
Functions
Ini * Ini_new (const char *ifname)
Open and read an initialization file, putting the information therein into a newly-allocated object of type Ini.
void Ini_print (Ini *ini, FILE *ofp)
Print object of type Ini to file ofp.
void Ini_free (Ini *ini)
Free object of type Ini.
double Ini_twoN0 (const Ini *ini)
Return the value of twoN in the 0th epoch.
int Ini_setDbl (const Ini *ini, const char *key, double *ptr, int mandatory)
Initialize *ptr to value corresponding to given key.
int Ini_setLong (const Ini *ini, const char *key, long *ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
int Ini_setInt (const Ini *ini, const char *key, int *ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
unsigned Ini_setUnsignedInt (const Ini *ini, const char *key, unsigned *ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
int Ini_setString (const Ini *ini, const char *key, char *ptr, int size, int mandatory)
Initialize *ptr do value corresponding to given key.
int Ini_setEpochLink (const Ini *ini, EpochLink **ptr, int mandatory)
Initialize linked list of Epochs from value (if any) specified in initialization file.
Detailed Description
Header for ini.c.
Author
Alan R. Rogers
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
Ini* Ini_new (const char * ifname)
Open and read an initialization file, putting the information therein into a newly-allocated object of type Ini.
Parameters
[in] ifname Name of input file
Returns
Newly-allocate Ini object containing info from input file.
References Ini::a, Assignment_new(), EpochLink_new(), Ini::epochList, strempty(), and stripComment().
void Ini_print (Ini * ini, FILE * ofp)
Print object of type Ini to file ofp.
References Ini::a, EpochLink_print(), and Ini::epochList.
int Ini_setDbl (const Ini * ini, const char * key, double * ptr, int mandatory)
Initialize *ptr to value corresponding to given key.
Parameters
[in] ini A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts execution if "key" is missing from Ini structure.
[out] ptr Points to a double variable, which will be initialized. If variable was set in initialization file, then this value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns
1 if variable was initialized, 0 otherwise.
References Ini::a, and Assignment_setDbl().
int Ini_setEpochLink (const Ini * ini, EpochLink ** ptr, int mandatory)
Initialize linked list of Epochs from value (if any) specified in initialization file.
Parameters
[in] ini A structure containing the values specified in the initialization file.
[in] mandatory If mandatory!=0, the function aborts execution if "key" is missing from Ini structure.
[out] ptr Points to variable to be initialized. If variable was set in initialization file, then this value will be written into *ptr. Otherwise, *ptr is unaltered. If ptr is initialized, it will point to a newly-allocated linked list of EpochLink structures, which must be freed by the calling routine.
Returns
1 if variable was initialized, 0 otherwise.
References EpochLink_dup(), and Ini::epochList.
int Ini_setInt (const Ini * ini, const char * key, int * ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters
[in] ini A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts execution if "key" is missing from Ini structure.
[out] ptr Points to a variable of type "int", which will be initialized. If variable was set in initialization file, then this value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns
1 if variable was initialized, 0 otherwise.
References Ini::a, and Assignment_setInt().
int Ini_setLong (const Ini * ini, const char * key, long * ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters
[in] ini A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts execution if "key" is missing from Ini structure.
[out] ptr Points to a variable of type "long int", which will be initialized. If variable was set in initialization file, then this value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns
1 if variable was initialized, 0 otherwise.
References Ini::a, and Assignment_setLong().
int Ini_setString (const Ini * ini, const char * key, char * ptr, int size, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters
[in] ini A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts execution if "key" is missing from Ini structure.
[out] ptr Points to a character array containing "size" bytes. If the variable "key" is assigned within "ini", its value will be copied into "ptr". Otherwise, *ptr is unaltered.
Returns
1 if variable was initialized, 0 otherwise.
References Ini::a, and Assignment_setString().
unsigned Ini_setUnsignedInt (const Ini * ini, const char * key, unsigned * ptr, int mandatory)
Initialize *ptr do value corresponding to given key.
Parameters
[in] ini A structure containing the assigned values.
[in] mandatory If mandatory!=0, the function aborts execution if "key" is missing from Ini structure.
[out] ptr Points to a variable of type "unsigned int", which will be initialized. If variable was set in initialization file, then this value will be written into *ptr. Otherwise, *ptr is unaltered.
Returns
1 if variable was initialized, 0 otherwise.
References Ini::a, and Assignment_setUnsignedInt().