ldpsiz: misc.c File Reference
misc.c File Reference
Miscellaneous functions.
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdarg.h>
#include <errno.h>
#include <ctype.h>
#include <assert.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_blas.h>
#include <unistd.h>
#include <execinfo.h>
#include "misc.h"
Defines
#define CALLSTACK_SIZE 128
Functions
int isopt (const char *shortOpt, const char *longOpt, const char *arg)
Return 1 if string arg matches either shortOpt or longOpt.
void tellopt (const char *opt, const char *description)
char * strlowercase (char *s)
Convert NULL-terminated string to lower case.
void checkmem (void *obj, const char *file, int line)
void assertFiniteArray (const double *x, size_t dim, const char *file, int line)
void printsqrmat (const char *msg, unsigned dim, double m[][dim])
void printgslmat (const char *msg, size_t dim, gsl_matrix *m)
int matIsFinite (unsigned dim, double m[][dim])
double getreldiff (int dim, double x[], double y[], int verbose)
char * strcenter (const char *text, unsigned width, char *buff, unsigned buffsize)
Center string "text" in a field of width "width".
int getNumCores (void)
long long_first_geq (long val, long *v, long len)
long long_last_leq (long val, long *v, long len)
void die (const char *msg, const char *file, int line)
void eprintf (const char *fmt,...)
void * memdup (const void *p, size_t n)
int strCountSetChunks (const char *str, const char *sep)
int strcomment (const char *s)
Return 1 if the first non-white char in string s is '#'; 0 otherwise.
char * stripComment (char *s)
strip comment ('#' to eol) from a string
int strempty (const char *s)
Return 1 if string contains only whitespace; 0 otherwise.
int dblEquals (double x, double y)
Test equality of x and y.
void dostacktrace (const char *file, int line, FILE *ofp)
double reflect (double x, double lo, double hi)
Fold x back and forth across the boundaries "lo" and "hi" to obtain a value y such that lo <= y <= hi.
void replaceSuffix (char *str, size_t str_size, const char *suffix, size_t suffix_len)
Replace suffix (part after last period) of string "str" with new suffix.
void unitTstResult (const char *facility, const char *result)
int compareLongs (const void *void_x, const void *void_y)
Compare two long ints.
int compareDoubles (const void *void_x, const void *void_y)
Compare two doubles.
int pr_gsl_vector (FILE *fp, const char *fmt, const gsl_vector *v)
Detailed Description
Miscellaneous functions.
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Function Documentation
int compareDoubles (const void * void_x, const void * void_y)
Compare two doubles.
Function interprets its arguments as pointers to doubles.
Parameters:
void_x,void_y Pointers to the two doubles, cast as pointers to voids.
Returns:
-1, 0, or 1 depending on whether the first arg is <, ==, or > the second.
Referenced by confidenceBounds().
int compareLongs (const void * void_x, const void * void_y)
Compare two long ints.
Function interprets its arguments as pointers to long ints.
Parameters:
void_x,void_y Pointers to the two integers, cast as pointers to voids.
Returns:
-1, 0, or 1 depending on whether the first arg is <, ==, or > the second.
Referenced by Boot_new().
int dblEquals (double x, double y)
Test equality of x and y.
In this test NaN == NaN, Inf == Inf, and -Inf == -Inf.
int isopt (const char * shortOpt, const char * longOpt, const char * arg)
Return 1 if string arg matches either shortOpt or longOpt.
ShortOpt and longOpt are ignored if their values are NULL. If arg doesn't match either shortOpt or longOpt, then return 0.
void replaceSuffix (char * str, size_t str_size, const char * suffix, size_t suffix_len)
Replace suffix (part after last period) of string "str" with new suffix.
If original string has no suffix, then append one to string. Abort if string isn't long enough.
char* strcenter (const char * text, unsigned width, char * buff, unsigned buffsize)
Center string "text" in a field of width "width".
The centered string is written into the character string "buff", whose size is "buffsize".
int strcomment (const char * s)
Return 1 if the first non-white char in string s is '#'; 0 otherwise.
int strempty (const char * s)
Return 1 if string contains only whitespace; 0 otherwise.
Referenced by Ini_new().