ldpsiz: misc.h File Reference
misc.h File Reference
Header for misc.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include "pophist.h"
#include <gsl/gsl_permutation.h>
#include <gsl/gsl_linalg.h>
#include <float.h>
#include <math.h>
#include <assert.h>
Defines
#define UNPHASED_HETEROZYGOTE 4
#define ERR(code, msg)
#define myassert(x) do { if (!(x)) { dostacktrace(__FILE__,__LINE__,stderr); assert(x); } } while(0)
#define REQUIRE(x, file, lineno)
Functions
static int Dbl_near (double x, double y)
Return 1 if the relative difference between x and y is less than or equal to DBL_EPSILON.
int isopt (const char *shortOpt, const char *longOpt, const char *arg)
Return 1 if string arg matches either shortOpt or longOpt.
void tellopt (const char *opt, const char *description)
char * strlowercase (char *s)
Convert NULL-terminated string to lower case.
void checkmem (void *obj, const char *file, int line)
void printsqrmat (const char *msg, unsigned dim, double m[][dim])
void printgslmat (const char *msg, size_t dim, gsl_matrix *m)
double getreldiff (int dim, double x[], double y[], int verbose)
int matIsFinite (unsigned dim, double m[][dim])
void assertFiniteArray (const double *x, size_t dim, const char *file, int line)
char * strcenter (const char *text, unsigned width, char *buff, unsigned buffsize)
Center string "text" in a field of width "width".
int strCountSetChunks (const char *str, const char *sep)
int getNumCores (void)
long long_first_geq (long val, long *v, long len)
long long_last_leq (long val, long *v, long len)
void die (const char *msg, const char *file, int line)
void eprintf (const char *fmt,...)
void * memdup (const void *p, size_t n)
int strempty (const char *s)
Return true if string contains only whitespace; false otherwise.
int strcomment (const char *s)
Return true if the first non-white char in string s is '#'; false otherwise.
char * stripComment (char *s)
strip comment ('#' to eol) from a string
int dblEquals (double x, double y)
Test equality of x and y.
void dostacktrace (const char *file, int line, FILE *ofp)
double reflect (double x, double lo, double hi)
Fold x back and forth across the boundaries "lo" and "hi" to obtain a value y such that lo <= y <= hi.
void replaceSuffix (char *str, size_t str_size, const char *suffix, size_t suffix_len)
Replace suffix (part after last period) of string "str" with new suffix.
int pr_gsl_vector (FILE *fp, const char *fmt, const gsl_vector *v)
unsigned hash (const char *s)
Hash a character string. Used for generating unique file names.
void unitTstResult (const char *facility, const char *result)
int compareLongs (const void *void_x, const void *void_y)
Compare two long ints.
int compareDoubles (const void *void_x, const void *void_y)
Compare two doubles.
long LInt_div_round (long num, long denom)
static int encodeDiploid (unsigned char *gtype, unsigned gtypeSize, const char *str)
Convert diploid genotype data from the character string format used in input to the binary format used internally.
static int encodeHaploid (unsigned char *gtype, unsigned gtypeSize, const char *str)
Convert haploid genotype data from the character string format used in input to the binary format used internally.
static unsigned encode01 (char c)
Encode a single character, which should equal either '0' or '1' on input.
int mystrcasecmp (const char *s1, const char *s2)
Detailed Description
Header for misc.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Define Documentation
#define ERR (code, msg)
Value:
do{\
    fprintf(stderr,"%s:%s:%d: %s %d (%s)\n",\
            __FILE__,__func__,__LINE__,\
            (msg), (code), strerror((code)));   \
    exit(1);\
}while(0)
#define REQUIRE (x, file, lineno)
Value:
do { \
  if (!(x)) { \
    dostacktrace(__FILE__,__LINE__,stderr); \
    eprintf("ERR@%s:%d->%s:%d: Sanity check FAIL\n",\
            (file),(lineno),__FILE__,__LINE__); \
   }\
} while(0)
Function Documentation
int compareDoubles (const void * void_x, const void * void_y)
Compare two doubles.
Function interprets its arguments as pointers to doubles.
Parameters:
void_x,void_y Pointers to the two doubles, cast as pointers to voids.
Returns:
-1, 0, or 1 depending on whether the first arg is <, ==, or > the second.
Referenced by confidenceBounds().
int compareLongs (const void * void_x, const void * void_y)
Compare two long ints.
Function interprets its arguments as pointers to long ints.
Parameters:
void_x,void_y Pointers to the two integers, cast as pointers to voids.
Returns:
-1, 0, or 1 depending on whether the first arg is <, ==, or > the second.
Referenced by Boot_new().
int dblEquals (double x, double y)
Test equality of x and y.
In this test NaN == NaN, Inf == Inf, and -Inf == -Inf.
static unsigned encode01 (char c) [inline, static]
Encode a single character, which should equal either '0' or '1' on input.
Returned value is 0 for '0', 1 for '1', and 255 for anything else.
Referenced by encodeDiploid(), and encodeHaploid().
static int encodeDiploid (unsigned char * gtype, unsigned gtypeSize, const char * str) [inline, static]
Convert diploid genotype data from the character string format used in input to the binary format used internally.
In the input string, a genotype may be any of the following: "00", "01", "10", "11", or "h". The four 2-character strings represent phased genotypes. The 1-character "h" is an unphased heterozygote. This function translates these codes into the integers 0, 1, 2, 3, and UNPHASED_HETEROZYGOTE. The latter value is a macro defined elsewhere.
Parameters:
[out] gtype an array of unsigned char values into which the binary-ecoded genotype values will be written.
[in] gtypeSize the size of the gtype array. No more than this number of genotypes will be written into the array.
[in] str The input, which represents genotypes as a NULL-terminated character string.
Returns:
The number of genotypes written into array gtype. This is *not* a NULL-terminated string, as the value 0 is valid in the interior of the array.
References encode01().
Referenced by Gtp_readSNP().
static int encodeHaploid (unsigned char * gtype, unsigned gtypeSize, const char * str) [inline, static]
Convert haploid genotype data from the character string format used in input to the binary format used internally.
In the input buffer a genotype may be either "0" or "1". This function translates these codes into the integers 0 and 1, using the function encode01.
Parameters:
[out] gtype an array of unsigned char values into which the binary-ecoded genotype values will be written.
[in] gtypeSize the size of the gtype array. No more than this number of genotypes will be written into the array.
[in] str The input, which represents genotypes as a NULL-terminated character string.
Returns:
The number of genotypes written into array gtype. This is *not* a NULL-terminated string, as the value 0 is valid in the interior of the array.
References encode01().
Referenced by Gtp_readSNP().
int isopt (const char * shortOpt, const char * longOpt, const char * arg)
Return 1 if string arg matches either shortOpt or longOpt.
ShortOpt and longOpt are ignored if their values are NULL. If arg doesn't match either shortOpt or longOpt, then return 0.
void replaceSuffix (char * str, size_t str_size, const char * suffix, size_t suffix_len)
Replace suffix (part after last period) of string "str" with new suffix.
If original string has no suffix, then append one to string. Abort if string isn't long enough.
char* strcenter (const char * text, unsigned width, char * buff, unsigned buffsize)
Center string "text" in a field of width "width".
The centered string is written into the character string "buff", whose size is "buffsize".
int strempty (const char * s)
Return true if string contains only whitespace; false otherwise.
Referenced by Ini_new(), and read_data().