ldpsiz: model.c File Reference
model.c File Reference
Functions for objects of type Model, a generic class whose details are implemented elsewhere.
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <pthread.h>
#include <gsl/gsl_odeiv2.h>
#include "misc.h"
#include "tokenizer.h"
#include "pophist.h"
#include "hill.h"
#include "strobeck.h"
#include "hayes.h"
#include "model.h"
Data Structures
struct ODE
Functions
static Model * Model_dup (const Model *model)
ODE * ODE_new (const Model *model, double abstol, double reltol)
void ODE_free (ODE *ode)
void * ODE_state (ODE *ode)
double ODE_stateVal (const ODE *ode, unsigned i)
size_t ODE_stateDim (const ODE *ode)
Model * ODE_model (ODE *ode)
struct dydt_params * ODE_dydtPar (ODE *ode)
double ODE_ld (ODE *ode, double c, double u, PopHist *ph)
Model * Model_alloc (const char *method, int twoNsmp)
Allocate a new Model of type specified by the character string "method".
void Model_free (Model *m)
Free an object of type Model.
void * Model_newState (const Model *m)
void Model_freeState (Model *m, void *state)
double Model_exactLD (const Model *model, ODE *ode, double c, double u, PopHist *ph)
void ODE_printState (const ODE *ode, FILE *fp)
Print state vector to file fp.
int ODE_evolve (ODE *ode, double *y, unsigned ydim, double c, double u, PopHist *ph, int dydt(double t_notused, const double y1[], double f[], void *params), int verbose)
Evolve through all Epochs of population history, beginning with initial state given in y.
void ODE_ldVec (ODE *ode, double *ld, int nbins, const double *c, double u, PopHist *ph)
On entry, c is a list of recombination rates, ph the population history, and odeStepSize is the initial step size.
double ODE_ldEq (ODE *ode, double c, double u, PopHist *ph, unsigned whichEpoch)
void ODE_ldVecEq (ODE *ode, double *eq, int nbins, const double *c, double u, PopHist *ph, int whichEpoch)
This function returns 1 vector: eq[i] is sigma_d^2 for a population at equilibrium with parameters as given in the specified PopHist Epoch, and recombination rate as specified by c[i].
ModelList * ModelList_alloc (const char *s0, int twoNsmp)
Allocate a new ModelList.
unsigned ModelList_addModel (ModelList *ml, const char *modelName, int twoNsmp)
Add a method to an ModelList.
void ModelList_free (ModelList *el)
Variables
pthread_mutex_t stderr_mutex = PTHREAD_MUTEX_INITIALIZER
Detailed Description
Functions for objects of type Model, a generic class whose details are implemented elsewhere.
The Model class generalizes the task of calculating the expected value of an LD statistic from parameter values involving recombination rate, c, mutation rate, u, and the history of population size.
Several of the models involve a vector of state variables, which is iterated forward from generation to generation. This file implements a function, odeEvolve, which approximates such systems as ODEs.
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
Model* Model_alloc (const char * method, int twoNsmp)
Allocate a new Model of type specified by the character string "method".
Parameters
[in] method character string representing a method to be used in predicting LD from population history. Legal values: "hill", "strobeck", and "hayes".
[in] twoNsmp haploid sample size, which is used to incorporate sampling bias into predicted values. To turn this feature off, use the value 0.
Returns
a pointer to a newly-allocated Model, if successful; or NULL, on failure.
References strlowercase().
Referenced by ModelList_addModel().
unsigned ModelList_addModel (ModelList * ml, const char * modelName, int twoNsmp)
Add a method to an ModelList.
Return 1 on success, 0 on failure.
Parameters
[out] ml The ModelList.
[in] modelName A character string such as "hill", or "strobeck".
[in] twoNsmp The number of individuals sampled.
References Model_alloc().
Referenced by ModelList_alloc().
ModelList* ModelList_alloc (const char * s0, int twoNsmp)
Allocate a new ModelList.
Parameters
[in] s0 A comma-separated list of Model types, such as "Hill,Strobeck".
References ModelList_addModel().
int ODE_evolve (ODE * ode, double * y, unsigned ydim, double c, double u, PopHist * ph, int dydtdouble t_notused, const double y1[], double f[],void *params, int verbose)
Evolve through all Epochs of population history, beginning with initial state given in y.
Calculation uses ODE approximation. The initial value of y should be set before calling ODE_evolve.
Parameters
[in,out] ode an object of type ODE.
[in,out] y Vector of state variables.
[in] odeStepSize Controls the size of step taken by the minimizer.
[in] ph Describes the population's history. If ph contains just one Epoch, y gets its equilibrium value.
[in] verbose Verbosity.
[in] c Recombination rate; overrides values in ph.
[in] u Mutation rate.
Returns
Returns 0 on success, 1 if function didn't run because dydt was not provided.
References PopHist_duration(), PopHist_nepoch(), and PopHist_twoN().
Referenced by Hill_sigdsq(), and Strobeck_sigdsq().
void ODE_ldVec (ODE * ode, double * ld, int nbins, const double * c, double u, PopHist * ph)
On entry, c is a list of recombination rates, ph the population history, and odeStepSize is the initial step size.
Parameters
[in,out] ode An object of type ODE.
[in] c,u Rates of recombination and mutation.
[in] nbins Size of arrays sigdsq and c.
[in] ph Population history.
[out] ld is a vector of "nbins" doubles. On return, the i'th entry will contain the value of sigma_d^2 implied by recombination rate c[i], and by the population history in argument "ph".
Referenced by costFun(), and lnObjFun().
void ODE_ldVecEq (ODE * ode, double * eq, int nbins, const double * c, double u, PopHist * ph, int whichEpoch)
This function returns 1 vector: eq[i] is sigma_d^2 for a population at equilibrium with parameters as given in the specified PopHist Epoch, and recombination rate as specified by c[i].
On entry, c is a list of recombination rates and ep the population history Epoch.
Parameters
[in,out] model An object of type Model, which specifies the method to be used in calculating expected LD.
void ODE_printState (const ODE * ode, FILE * fp)
Print state vector to file fp.