ldpsiz: pophist.c File Reference
pophist.c File Reference
Functions for objects of type PopHist, which represent the history of population size.
#include "misc.h"
#include "pophist.h"
#include <assert.h>
#include <gsl/gsl_randist.h>
#include <gsl/gsl_rng.h>
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Data Structures
struct PopHist
PopHist represents the history of a single population.
struct EpochLink
Population history represented as a linked list of epochs.
Defines
#define PAR_PER_EPOCH 2
The number of parameters in each Epoch.
Functions
static int isPopSize (int ndx)
Return true if index refers to a population size parameter.
void PopHist_sanityCheck (PopHist *ph, const char *file, int lineno)
void EpochLink_print (int ndx, const EpochLink *link, FILE *ofp)
Print a linked list.
EpochLink * EpochLink_new (EpochLink *head, double t, double twoN)
Insert a new link into the list.
EpochLink * EpochLink_dup (EpochLink *head)
Return a newly allocated copy of a linked list of epochs.
void EpochLink_free (EpochLink *link)
free linked list
int EpochLink_nlinks (const EpochLink *head)
Count the number of links in a linked list of EpochLink objects.
const EpochLink * EpochLink_next (const EpochLink *link)
Return a pointer to the next link in a chain of EpochLinks.
double EpochLink_duration (const EpochLink *link)
Return time value from given link.
double EpochLink_twoN (const EpochLink *link)
Return twoN value from given link.
void EpochLink_test (void)
void PopHist_init (PopHist *ph, unsigned nepoch, size_t size)
Set up a PopHist object, which has previously been allocated as a contiguous memory block.
PopHist * PopHist_newEmpty (unsigned nepoch)
Allocate an empty PopHist.
size_t PopHist_size (const PopHist *ph)
Return the size of the memory block on which `ph` is allocated.
size_t PopHist_calcSize (unsigned nepoch)
Return the number of bytes occupied by a PopHist with "nepoch" epochs.
double PopHist_duration (const PopHist *ph, int i)
Return duration of Epoch i.
double PopHist_age (const PopHist *ph, int i)
Return time from leaves to the most recent end of Epoch i.
double PopHist_twoN (const PopHist *ph, int i)
Return the haploid population size, 2N, during epoch i.
int PopHist_findEpoch (const PopHist *ph, double age)
Find epoch that covers a given age.
double PopHist_twoNinv (const PopHist *ph, int i)
Return 1/2N for the relevant epoch.
void PopHist_setDuration (PopHist *ph, int i, double duration)
Set duration of the i'th epoch of PopHist structure ph.
void PopHist_setTwoN (PopHist *ph, int i, double twoN)
Set population size during the i'th epoch of PopHist structure ph.
void PopHist_setTwoNinv (PopHist *ph, int i, double twoNinv)
Set 1/2N during the i'th epoch of PopHist structure ph.
PopHist * PopHist_fromEpochLink (const EpochLink *head)
Allocate a new PopHist and initialize from a chain of EpochLink objects.
unsigned PopHist_nepoch (const PopHist *ph)
return the number of epochs
void PopHist_print_comment (const PopHist *ph, const char *comstr, FILE *outfile)
Print PopHist, preceding each line with a comment string.
void PopHist_print (const PopHist *ph, FILE *outfile)
Print a PopHist object.
void PopHist_free (PopHist *ph)
Destroy a PopHist object.
int PopHist_calc_nParams (int nepoch)
This is just like PopHist_nParams, except that you don't need to allocate a PopHist object before calling it.
unsigned PopHist_nParams (const PopHist *ph)
Return the number of parameters in a PopHist.
int PopHist_paramName (const PopHist *ph, char *buff, int bufflen, int ndx)
Return the name of a given PopHist parameter.
double PopHist_paramValue (const PopHist *ph, int ndx)
Return the value of a given PopHist parameter.
void PopHist_to_vector (gsl_vector *v, const PopHist *ph)
Put PopHist parameters into a gsl_vector.
void PopHist_to_C_array (int dim, double v[dim], const PopHist *ph)
Put PopHist parameters into an ordinary C array.
void PopHist_setAllTwoNinv (double *x, int dim, double value)
Assign the same value to all positions in array corresponding to twoNinv values in the parameter vector of a PopHist object.
void PopHist_setAllDuration (double *x, int dim, double value)
Assign the same value to all positions in array corresponding to duration values in the parameter vector of a PopHist object.
void PopHist_setSimplexScale (gsl_vector *scale, const PopHist *ph)
Set scale vector used by simplex algorithm.
void vector_to_PopHist (PopHist *ph, const gsl_vector *v)
Adjust the parameters in PopHist structure ph to reflect the values in gsl vector p.
void C_array_to_PopHist (PopHist *ph, int dim, const double *v)
Adjust the parameters in PopHist structure ph to reflect the values in C array p, of dimension "dim".
PopHist * PopHist_dup (const PopHist *ph)
Return a pointer to a newly allocated copy of PopHist structure ph.
void PopHist_copy (PopHist *dest, const PopHist *src)
Copy PopHist src into dest.
PopHist * PopHist_perturb (PopHist *ph, const PopHist *ph0, double dt, double dNinv, gsl_rng *rng)
Fill ph with random values based on ph0.
PopHist * PopHist_perturbInPlace (PopHist *ph, double dt, double dNinv, gsl_rng *rng)
Perturb parameters in PopHist structure ph.
double PopHist_distance (PopHist *ph1, PopHist *ph2)
Measure the distance between two PopHist objects.
Variables
static const char * epochParamName [] = { "twoN", "t" }
Names of the parameters within each lpoch.
Detailed Description
Functions for objects of type PopHist, which represent the history of population size.
Author:
Alan R. Rogers The entire history of population size, represented as a sequence of Epochs. Population parameters may change at Epoch boundaries but are constant within epochs.
In this version, all parameters are in a single array, and twoN parameters are coded as 1/twoN.
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
EpochLink* EpochLink_dup (EpochLink * head)
Return a newly allocated copy of a linked list of epochs.
References EpochLink_dup().
Referenced by EpochLink_dup(), and Ini_setEpochLink().
double EpochLink_duration (const EpochLink * link)
Return time value from given link.
Referenced by PopHist_fromEpochLink().
EpochLink* EpochLink_new (EpochLink * head, double t, double twoN)
Insert a new link into the list.
Add item to linked list, allocating as necessary.
Returns:
pointer to head of list.
Referenced by Ini_new().
int EpochLink_nlinks (const EpochLink * head)
Count the number of links in a linked list of EpochLink objects.
Parameters:
head pointer to beginning of linked list.
Returns:
Number of links in the chain beginning with "head".
References EpochLink_nlinks().
Referenced by EpochLink_nlinks(), and PopHist_fromEpochLink().
void EpochLink_print (int ndx, const EpochLink * link, FILE * ofp)
Print a linked list.
Parameters:
ndx A state variable, which should be zero in the top-level call.
link Pointer to the head of the linked list.
ofp Pointer to output file.
References EpochLink_print().
Referenced by EpochLink_print(), and Ini_print().
double EpochLink_twoN (const EpochLink * link)
Return twoN value from given link.
Referenced by Ini_twoN0(), and PopHist_fromEpochLink().
double PopHist_age (const PopHist * ph, int i)
Return time from leaves to the most recent end of Epoch i.
Thus, PopHist_age(ph, 0) is 0 and PopHist_age(ph, PopHist_nepoch(ph)) gives the sum of all epoch durations except the final infinite one.
References PopHist_duration().
int PopHist_calc_nParams (int nepoch)
This is just like PopHist_nParams, except that you don't need to allocate a PopHist object before calling it.
All you need is the number of epochs.
References PAR_PER_EPOCH.
Referenced by PopHist_nParams().
void PopHist_copy (PopHist * dest, const PopHist * src)
Copy PopHist src into dest.
The two must have equal values of nepoch. Otherwise, the function aborts.
Parameters:
src The source PopHist.
dest The destination PopHist.
References PopHist::size.
Referenced by Chain_bestFit(), Chain_publish(), ChainState_new(), and PopHist_perturb().
void PopHist_free (PopHist * ph)
Destroy a PopHist object.
Referenced by Chain_free().
PopHist* PopHist_fromEpochLink (const EpochLink * head)
Allocate a new PopHist and initialize from a chain of EpochLink objects.
Parameters:
[in] head Beginning of chain of EpochLink objects.
References EpochLink_duration(), EpochLink_next(), EpochLink_nlinks(), EpochLink_twoN(), PopHist::nepoch, PopHist_duration(), PopHist_newEmpty(), PopHist_setDuration(), and PopHist_setTwoN().
PopHist* PopHist_newEmpty (unsigned nepoch)
Allocate an empty PopHist.
The parameters of each epoch are initialized with zeroes, except for the duration of the final (earliest) epoch, which is infinite.
Parameters:
[in] nepoch Number of epochs in the new PopHist.
Returns:
a pointer to a newly allocated PopHist object with default values.
References PopHist_calcSize(), and PopHist_init().
Referenced by PopHist_fromEpochLink().
unsigned PopHist_nParams (const PopHist * ph)
Return the number of parameters in a PopHist.
There are two adjustable parameters per epoch: N and t, except that t is fixed at infinity in the earliest epoch. The number of adjustable parameters is therefore 2*nepochs - 1.
References PopHist::nepoch, and PopHist_calc_nParams().
Referenced by C_array_to_PopHist(), Chain_printHdr(), Chain_printState(), costFun(), Hill_sigdsq(), PopHist_paramName(), PopHist_paramValue(), PopHist_to_C_array(), PopHist_to_vector(), prHeader(), TaskArg_new(), and vector_to_PopHist().
int PopHist_paramName (const PopHist * ph, char * buff, int bufflen, int ndx)
Return the name of a given PopHist parameter.
Parameters:
[in] ph A pointer to a PopHist. It is used only to determine the number of epochs.
[out] buff A character buffer into which the parameter's name will be written. If bufflen is too short, the name will be truncated.
[in] bufflen The length of the buffer.
[in] ndx The index of the parameter, a positive integer less than the number of PopHist parameters, as given by PopHist_nParams.
Returns:
0 on success, 1 on failure.
References epochParamName, PAR_PER_EPOCH, and PopHist_nParams().
Referenced by Chain_printHdr(), costFun(), Hill_sigdsq(), and prHeader().
double PopHist_paramValue (const PopHist * ph, int ndx)
Return the value of a given PopHist parameter.
Parameters:
[in] ph A pointer to a PopHist.
[in] ndx The index of the parameter, a positive integer less than the number of PopHist parameters, as given by PopHist_nParams.
Returns:
Value of specified parameter within ph.
References isPopSize(), PopHist::p, and PopHist_nParams().
Referenced by Chain_printState(), and costFun().
PopHist* PopHist_perturb (PopHist * ph, const PopHist * ph0, double dt, double dNinv, gsl_rng * rng)
Fill ph with random values based on ph0.
ph0 is first copied into ph. Then ph is perturbed as described in the documentation to PopHist_perturbInPlace.
Parameters:
[out] ph PopHist into which new values will be written.
[in] ph0 PopHist whose values are perturbed to obtain new values. The values within ph0 are unchanged.
[in] dt controls the magnitude of perturbations in the duration variable.
[in] dNinv controls the magnitude of perturbations in population size.
[in] rng random number generator.
Returns:
ph
References PopHist_copy(), and PopHist_perturbInPlace().
PopHist* PopHist_perturbInPlace (PopHist * ph, double dt, double dNinv, gsl_rng * rng)
Perturb parameters in PopHist structure ph.
Each parameter is perturbed away from its initial value. The distribution of the perturbations depends on the macros PERTURB_GAUSSIAN and PERTURB_TDIST. If the first of these is defined at compile time, then perturbations are Gaussian. Otherwise, if the second macro is defined, perturbations are drawn from a t distribution. Otherwise they are uniform.
1/2N values are reflected back and forth so that the perturbed value lies within [loTwoNinv, hiTwoNinv].
Parameters:
[in,out] ph The PopHist to be perturbed.
[in] dt controls the magnitude of perturbations in the duration variable.
[in] dNinv controls the magnitude of perturbations in 1/2N.
[in] rng random number generator.
Returns:
ph
References PopHist::nepoch, PopHist_duration(), PopHist_setDuration(), PopHist_setTwoNinv(), PopHist_twoNinv(), and reflect().
Referenced by PopHist_perturb().
void PopHist_print (const PopHist * ph, FILE * outfile)
Print a PopHist object.
Parameters:
ph PopHist to print.
outfile Output file.
References PopHist_print_comment().
Referenced by costFun().
void PopHist_print_comment (const PopHist * ph, const char * comstr, FILE * outfile)
Print PopHist, preceding each line with a comment string.
Parameters:
ph PopHist to print.
comstr Comment string to prepend to each line of output.
outfile Output file.
References PopHist::nepoch, PopHist_duration(), and PopHist_twoN().
Referenced by Chain_printFull(), and PopHist_print().
void PopHist_setDuration (PopHist * ph, int i, double duration)
Set duration of the i'th epoch of PopHist structure ph.
Parameters:
[out] ph PopHist object to be modified.
[in] i index of epoch to be modified. Must be less than ph->nepoch-1.
[in] duration new value of duration of i'th epoch.
References PopHist::nepoch, PopHist::p, and PAR_PER_EPOCH.
Referenced by PopHist_fromEpochLink(), PopHist_perturbInPlace(), and vector_to_PopHist().
void PopHist_setSimplexScale (gsl_vector * scale, const PopHist * ph)
Set scale vector used by simplex algorithm.
Each entry receives a value that represents the expected magnitude of the corresponding parameter in PopHist.
Parameters:
[in] PopHist object.
[out] scale gsl_vector into which paramters will be written.
References PopHist::nepoch.
void PopHist_setTwoN (PopHist * ph, int i, double twoN)
Set population size during the i'th epoch of PopHist structure ph.
Parameters:
[out] ph PopHist object to be modified.
[in] i index of epoch to be modified. Must be less than ph->nepoch-1.
[in] t new value of duration of i'th epoch.
References PopHist::p, and PAR_PER_EPOCH.
Referenced by PopHist_fromEpochLink().
void PopHist_setTwoNinv (PopHist * ph, int i, double twoNinv)
Set 1/2N during the i'th epoch of PopHist structure ph.
Parameters:
[out] ph PopHist object to be modified.
[in] i index of epoch to be modified. Must be less than ph->nepoch-1.
[in] t new value of duration of i'th epoch.
References PopHist::p, and PAR_PER_EPOCH.
Referenced by PopHist_perturbInPlace(), and vector_to_PopHist().
size_t PopHist_size (const PopHist * ph)
Return the size of the memory block on which `ph` is allocated.
References PopHist::size.
void PopHist_to_C_array (int dim, double v[dim], const PopHist * ph)
Put PopHist parameters into an ordinary C array.
Parameters:
[in] PopHist object.
[out] v An array into which paramters will be written.
[in] dim The dimension of array v
References PopHist::p, and PopHist_nParams().
void PopHist_to_vector (gsl_vector * v, const PopHist * ph)
Put PopHist parameters into a gsl_vector.
Parameters:
[in] PopHist object.
[out] v gsl_vector into which paramters will be written.
References PopHist::p, and PopHist_nParams().
double PopHist_twoN (const PopHist * ph, int i)
Return the haploid population size, 2N, during epoch i.
References PopHist::p, and PAR_PER_EPOCH.
Referenced by Hill_evolveDiscrete(), Hill_sigdsq(), Hill_sigdsqEq(), MatCoal_integrate(), ODE_evolve(), PopHist_distance(), PopHist_print_comment(), Strobeck_evolveDiscrete(), Strobeck_sigdsq(), and Strobeck_sigdsqEq().