ldpsiz: readgtp.c File Reference
readgtp.c File Reference
Parse files written in .gtp format, which are used as input by eld.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>
#include <math.h>
#include <pthread.h>
#include <assert.h>
#include <limits.h>
#include "tokenizer.h"
#include "misc.h"
#include "fileindex.h"
#include "assign.h"
#include "readgtp.h"
Functions
Assignment * Gtp_readHdr (FILE *ifp)
Read header of file ifp in order to parse assignment statements.
int Gtp_readSNP (FILE *ifp, char *snpId, size_t snpIdSize, double *mappos, char *alleles, size_t allelesSize, unsigned char *sitedat, size_t sitedatSize, int isDiploid)
Read a SNP from the GTP output file.
Detailed Description
Parse files written in .gtp format, which are used as input by eld.
Author
Alan R. Rogers
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
Assignment* Gtp_readHdr (FILE * ifp)
Read header of file ifp in order to parse assignment statements.
These assignments are stored an a structure of class Assignment, which is returned to the calling function.
Parameters
[in] ifp Points to input file stream.
Returns
pointer to Assignment structure.
Side Effects:
The file pointer ifp is positioned so that the next line read will be the first SNP.
References Assignment_new().
Referenced by FileIndex_readFile().
int Gtp_readSNP (FILE * ifp, char * snpId, size_t snpIdSize, double * mappos, char * alleles, size_t allelesSize, unsigned char * sitedat, size_t sitedatSize, int isDiploid)
Read a SNP from the GTP output file.
Return 0 on success, 1 on failure.
Parameters
[in] ifp Points to input file stream.
[out] snpId Character buffer to hold the string that identifies current SNP.
[in] snpIdSize Size of snpId. If snpIdSize==0, nothing will be written into snpId. In this case, it is OK to pass NULL for the value of snpId.
[out] mappos Map position of current SNP in centimorgans.
[out] alleles This string will contain a list of the alleles present at current SNP.
[in] allelesSize Size of "alleles". If allelesSize==0, nothing will be written into alleles. In this case, it is OK to pass NULL for the value of alleles.
[out] sitedat Unsigned character buffer whose i'th entry will hold the genotype data for the i'th individual. This value is an integer that encodes genotypic values as described in the documentation of function encodeGtype, defined in file misc.h.
[in] sitedatSize Size of the sitedat array.
[in] isDiploid The data are assumed to be diploid if isDiploid is nonzero. Otherwise, haploidy is assumed.
Returns
A positive number (the number of genotypes) on success, but a negative number (EOF) on end of file.
References encodeDiploid(), and encodeHaploid().
Referenced by FileIndex_readFile(), and Window_nextSNP().