ldpsiz: sald.c File Reference
sald.c File Reference
use simplex-simulated annealing to estimate population history
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include <gsl/gsl_rng.h>
#include <gsl/gsl_randist.h>
#include <float.h>
#include <getopt.h>
#include <pthread.h>
#include <string.h>
#include <time.h>
#include <limits.h>
#include "misc.h"
#include "boot.h"
#include "pophist.h"
#include "sasimplex.h"
#include "tokenizer.h"
#include "jobqueue.h"
#include "hill.h"
#include "ini.h"
#include "model.h"
#include "assign.h"
#include "annealsched.h"
Data Structures
struct TaskArg
The total job is divided into tasks, which are placed on a queue.
struct CostPar
Parameters of cost function–that which is minimized.
Macros
#define DPRINTF(arg)
Functions
void usage (void)
int read_data (FILE *ifp, int nbins, double *cm, double *sigdsq)
Read the data file produced by eld.
TaskArg * TaskArg_new (unsigned task, unsigned seed, int nbins, double u, double ftol, double xtol, double *stepsize, AnnealSched *sched, double *loBnd, double *hiBnd, double *hiInit, double odeAbsTol, double odeRelTol, int nPerTmptr, int verbose, double *sigdsq_obs, double *c, Model *model, PopHist *ph_init, int randomStart)
Construct a new TaskArg.
void TaskArg_free (TaskArg *targ)
int taskfun (void *varg)
static double costFun (const gsl_vector *x, void *varg)
Sum of differences between observed and expected sigma_d^2 vectors.
void CostPar_print (CostPar *cp)
TaskArg * TaskArg_best (TaskArg **tpvec, int n)
Given a vector of TaskArg pointers, return a pointer to the one with lowest cost among those that have converged.
void prHeader (PopHist *ph)
Print header.
int main (int argc, char **argv)
Variables
const int setSimplexVersion
pthread_mutex_t stdoutLock = PTHREAD_MUTEX_INITIALIZER
Detailed Description
use simplex-simulated annealing to estimate population history
sald: use simplex-simulated annealing to estimate population history
To estimate the parameters describing population history, we need to find values that provide the best fit to LD data. This involves maximization on a complex surface with lots of local peaks. (To verify this for yourself, see mcmcld.) To avoid getting stuck on local peaks, sald uses the simplex version of simulated annealing.
Usage
The input data file should be as produced by eld.
Although simulated annealing works pretty well, I often find that different runs end up on different peaks. Therefore, sald is able to launch multiple simulated annealing jobs, each from a random starting point. These can run in parallel, on separate threads. The number of parallel optimizers is set using the --nOpt argument described below.
The program also deals with bootstrap data, as provided by eld. The various boostrap data sets also run in parallel if your machine has multiple cores. By default sald does not process bootstrap replicates: use --bootfile if you want it to.
By default sald uses as many threads as your machine has cores. This is not a good idea if you are sharing a machine with other users. Set the number of threads to some smaller number using --threads. On linux or osx, you can use top to figure out how many threads are actually running. If you launch 20 threads but only 10 run at any given time, your job will run slower. Stop it and launch again with --threads 10.
Simulated annealing works by beginning with a flattened version of your objective function. In this flattened version, all the peaks are smaller, so it is easy for the simplex to move from peak to peak. The extent of flattening is controlled by a parameter called "temperature". High temperature corresponds to lots of flattening. The annealing algorithm runs for awhile at a high temperature, then lowers the temperature and runs awhile more. The succession of temperatures and the number of iterations at each temperature is called the "annealing schedule". You can change the performance of the algorithm by adjusting this schedule. See the --initTmptr, --nPerTmptr and --tmptrDecay arguments.
usage: sald [options] input_file_name
   where options may include:
   -m <method> or --methods <method>
      specify method "Hill", or "Strobeck", or "Hill,Strobeck"
   -n <x> or --twoNsmp <x>
      haploid sample size
   -t <x> or --threads <x>
      number of threads (default is auto)
   -u <x> or --mutation <x>
      mutation rate/generation
   -v <x> or --verbose
      more output
   -f <x> or --bootfile <x>
      read bootstrap file x
   -c <x> or --confidence <x>
      specify confidence level for CIs of parameters
   --twoN <x>
      haploid pop size to x in current epoch
   -T <x> or --time <x>
      length of current epoch (generations)
   -E or --nextepoch
      move to next earlier epoch
   --noRandomStart
      Don't initialize PopHist at random
   --nOpt <x>
      optimizers per data set
   --initTmptr <x>
      initial temperature
   --nTmptrs <x>
      number of temperatures
   --tmptrDecay <x>
      ratio of successive temperatures
   -i <x> or --nItr <x>
      total number of iterations
   -h or --help
      print this message
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
static double costFun (const gsl_vector * x, void * varg) static
Sum of differences between observed and expected sigma_d^2 vectors.
Parameters
[in] ph Current population history
[in] u mutation rate per site per generation
[in] nbins Number of values in vectors obs and c
[in] sigdsq Vector of nbins values, the observed values of sigdsq.
[in] c Vector of nbins values, the recombination rates associated with the values in sigdsq.
References ODE_ldVec(), PopHist_nParams(), PopHist_paramName(), PopHist_paramValue(), PopHist_print(), and vector_to_PopHist().
int read_data (FILE * ifp, int nbins, double * cm, double * sigdsq)
Read the data file produced by eld.
Parameters
[in] ifp Points to file produced by eld.
[in] nbins The length of all arrays.
[out] cm An array giving the average separation (in centimorgans) between pairs of SNPs within the various bins.
[out] sigdsq An array of estimates of sigma_d^2.
Returns
number of lines read