ldpsiz: strobeck.c File Reference
strobeck.c File Reference
Calculate sigma_d^2 using recurrence equations of Strobeck and Morgan (1978), and Hudson (1985).
#include <stdio.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_matrix.h>
#include "pophist.h"
#include "misc.h"
#include "model.h"
#include "string.h"
#include "strobeck.h"
Data Structures
struct param_struct
struct StrobeckData
Macros
#define DIM 5
Functions
double Strobeck_exactLD (double c, double u, PopHist *ph, int twoNsmp, void *data)
static int onestep (const double yy1[], double y2[], double twoN, double c, double u)
Move the state vector forward one generation, using recurrence equations of Strobeck and Morgan (1978, see Eqn 3, p 833).
static int iterate (double y[], int t, double twoN, double c, double u)
Iterate the difference equation across t generations.
static void geteq_c_mid (double x[DIM], double twoN, double c, double u, double fourNu)
void * StrobeckData_new (void)
double StrobeckData_stateVal (void *vdata, unsigned i)
i'th state value
void StrobeckData_free (void *p)
Model * Model_allocStrobeck (int twoNsmp)
double Strobeck_sigdsqEq (double c, double u, PopHist *ph, unsigned whichEpoch, int twoNsmp, void *vdata)
Set state vector to equilibrium for epoch "whichEpoch" and then use it to calculate sigmdsq.
double Strobeck_sigdsq (ODE *ode, double c, double u, PopHist *ph, int twoNsmp)
Set state vector to initial equilibrium, then evolve it through the population history, and then use this state vector to calculate sigmdsq.
size_t Strobeck_stateDim (void)
const char * Strobeck_stateLbl (unsigned i)
int Strobeck_dydt (double t_notused, const double yy1[], double f[], void *params)
This function calculates the difference, from one generation to the next, for each of the 5 identity coefficients.
int Strobeck_geteq (double x[], double twoN, double c, double u)
Fill x vector with equilibrium values given on pp 833-834 of Strobeck and Morgan.
double Strobeck_get_sigdsq (double y[], int twoNsmp)
Calculate sigma_d^2 from state vector.
int Strobeck_evolveDiscrete (double y[], PopHist *ph, double c, double u)
Evolve through all epochs of population history, using step size h and beginning with initial equilibrium.
Variables
static const char * stateLbl [DIM]
Detailed Description
Calculate sigma_d^2 using recurrence equations of Strobeck and Morgan (1978), and Hudson (1985).
Author
Alan R. Rogers Strobeck and Morgan. 1978. The effect of intragenic recombination on the number of alleles in a finite population. Genetics 88: 829-844.
It also uses formula A6 (p 630) from
Hudson, Richard R. 1985. The sampling distribution of linkage disequilibrium under an infinite allele model without selection. Genetics, 109(3): 611-631.
Hudson showed that E[D^2] = Phi_AB - 2 Gamma_AB + Delta_AB
The parameter sigma_d^2 was defined by
Ohta, T. and Kimura, Motoo. 1971. Linkage disequilibrium between two segregating nucleotide sites under the steady flux of mutations in a finite population. Genetics 68(4): 571–580.
They defined it like this
sigma_d^2 = E[D^2]/E[(1-J_A)(1-J_B)]
where J_A = sum a_i^2, and J_B = sum b_i^2, where a_i and b_i are allele frequencies of the current generation at loci A and B. The denominator is thus the probability that two random genes from locus A differ, and two genes drawn independently from locus B also differ.
It can also be shown (I haven't found this in the literature) that
E[(1-J_A)(1-J_B)] = 1 - PhiA - PhiB + DeltaAB
The code below uses the formulas of Strobeck and Morgan to calculate the 5 identity coefficients, then uses these to calculate sigma_d^2.
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
static int onestep (const double yy1[], double y2[], double twoN, double c, double u) static
Move the state vector forward one generation, using recurrence equations of Strobeck and Morgan (1978, see Eqn 3, p 833).
Parameters
input] yy1 is the initial state vector.
output] y2 is the new state vector.
Referenced by iterate(), Strobeck_dydt(), and Strobeck_get_sigdsq().
int Strobeck_dydt (double t_notused, const double yy1[], double f[], void * params)
This function calculates the difference, from one generation to the next, for each of the 5 identity coefficients.
It is based on equation 3 of Strobeck and Morgan.
y[0] = phiA y[1] = phiB y[2] = phiAB y[3] = gammaAB y[4] = deltaAB
Parameters
[in] y1 is the current vector of identity coefficients.
[out] f will contain the derivatives of y[], as approximated by the difference equations of Strobeck and Morgan.
[in] params points to a structure of type param_struct.
References onestep().
Referenced by Strobeck_sigdsq().
int Strobeck_evolveDiscrete (double y[], PopHist * ph, double c, double u)
Evolve through all epochs of population history, using step size h and beginning with initial equilibrium.
Calculation iterates difference equation. The initial value of y is set to equilibrium equation for equilibrium.
Parameters
[out] y On return, y contains Hill's vector of moments.
[in] ph Describes the population's history. If ph contains just one epoch, y gets its equilibrium value.
[in] c Recombination rate; overrides values in ph.
[in] u Mutation rate.
Returns
Always returns 0.
References iterate(), PopHist_duration(), PopHist_nepoch(), PopHist_twoN(), and Strobeck_geteq().
double Strobeck_get_sigdsq (double y[], int twoNsmp)
Calculate sigma_d^2 from state vector.
The formulas involved are in the comment at the top of this file.
Parameters
[in] y State vector, whose entries represent PhiA, PhiB, PhiAB, GammaAB, and DeltaAB.
[in] n Number of gene copies in sample. If n==0, then no bias correction is done.
References onestep().
Referenced by Strobeck_sigdsq(), and Strobeck_sigdsqEq().
int Strobeck_geteq (double x[], double twoN, double c, double u)
Fill x vector with equilibrium values given on pp 833-834 of Strobeck and Morgan.
Strobeck and Morgan separate 3 cases, for c << u, c >> u, and c ~= u. I did some experiments to figure out how to bound these ranges, and decided never to use the formula for large c.
Referenced by Strobeck_evolveDiscrete(), Strobeck_sigdsq(), and Strobeck_sigdsqEq().
Variable Documentation
const char* stateLbl[DIM] static
Initial value:
= { "phiA",
    "phiB",
    "phiAB",
    "gammaAB",
    "deltaAB"
}