ldpsiz: strobeck.h File Reference
strobeck.h File Reference
Header for strobeck.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
#include "typedefs.h"
#include "pophist.h"
Functions
void * StrobeckData_new (void)
void StrobeckData_free (void *p)
double StrobeckData_stateVal (void *vdata, unsigned i)
i'th state value
int Strobeck_geteq (double x[], double twoN, double c, double u)
Fill x vector with equilibrium values given on pp 833-834 of Strobeck and Morgan.
int Strobeck_dydt (double t, const double y[], double f[], void *params)
This function calculates the difference, from one generation to the next, for each of the 5 identity coefficients.
double Strobeck_get_sigdsq (double y[], int n)
Calculate sigma_d^2 from state vector.
int Strobeck_evolveDiscrete (double y[], PopHist *ph, double c, double u)
Evolve through all epochs of population history, using step size h and beginning with initial equilibrium.
double Strobeck_sigdsq (ODE *ode, double c, double u, PopHist *ph, int twoNsmp)
Set state vector to initial equilibrium, then evolve it through the population history, and then use this state vector to calculate sigmdsq.
double Strobeck_sigdsqEq (double c, double u, PopHist *ph, unsigned whichEpoch, int twoNsmp, void *data)
Set state vector to equilibrium for epoch "whichEpoch" and then use it to calculate sigmdsq.
size_t Strobeck_stateDim (void)
const char * Strobeck_stateLbl (unsigned i)
Model * Model_allocStrobeck (int twoNsmp)
Detailed Description
Header for strobeck.c
Copyright:
Copyright (c) 2014, Alan R. Rogers <rogers@anthro.utah.edu>. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Author:
Alan R. Rogers
Function Documentation
int Strobeck_dydt (double t_notused, const double yy1[], double f[], void * params)
This function calculates the difference, from one generation to the next, for each of the 5 identity coefficients.
It is based on equation 3 of Strobeck and Morgan.
y[0] = phiA y[1] = phiB y[2] = phiAB y[3] = gammaAB y[4] = deltaAB
Parameters:
[in] y1 is the current vector of identity coefficients.
[out] f will contain the derivatives of y[], as approximated by the difference equations of Strobeck and Morgan.
[in] params points to a structure of type param_struct.
References onestep().
Referenced by Strobeck_sigdsq().
int Strobeck_evolveDiscrete (double y[], PopHist * ph, double c, double u)
Evolve through all epochs of population history, using step size h and beginning with initial equilibrium.
Calculation iterates difference equation. The initial value of y is set to equilibrium equation for equilibrium.
Parameters:
[out] y On return, y contains Hill's vector of moments.
[in] ph Describes the population's history. If ph contains just one epoch, y gets its equilibrium value.
[in] c Recombination rate; overrides values in ph.
[in] u Mutation rate.
Returns:
Always returns 0.
References iterate(), PopHist_duration(), PopHist_nepoch(), PopHist_twoN(), and Strobeck_geteq().
double Strobeck_get_sigdsq (double y[], int twoNsmp)
Calculate sigma_d^2 from state vector.
The formulas involved are in the comment at the top of this file.
Parameters:
[in] y State vector, whose entries represent PhiA, PhiB, PhiAB, GammaAB, and DeltaAB.
[in] n Number of gene copies in sample. If n==0, then no bias correction is done.
References onestep().
Referenced by Strobeck_sigdsq(), and Strobeck_sigdsqEq().
int Strobeck_geteq (double x[], double twoN, double c, double u)
Fill x vector with equilibrium values given on pp 833-834 of Strobeck and Morgan.
Strobeck and Morgan separate 3 cases, for c << u, c >> u, and c ~= u. I did some experiments to figure out how to bound these ranges, and decided never to use the formula for large c.
Referenced by Strobeck_evolveDiscrete(), Strobeck_sigdsq(), and Strobeck_sigdsqEq().