ldpsiz: window.h File Reference
window.h File Reference
Header for window.c.
#include <stdio.h>
#include "typedefs.h"
#include "boot.h"
#include "em.h"
#include "misc.h"
Data Structures
struct SNP
Estimate the linkage disequilibrium (LD) between single nucleotide polymorphisms (SNPs) as a function of the map distance between those SNPs.
Functions
void SNP_clear (SNP *snp)
Set values to initial states.
SNP * SNP_connect (SNP *list1, SNP *list2)
Connect list2 to the tail of list1 and return a pointer to list1.
int SNP_count (SNP *snp)
Count SNPs in linked list.
void SNP_free (SNP *snp)
free linked list of SNPs
double SNP_getDsq (double *pqpq, SNP *x, SNP *y, unsigned ploidy)
Calculate D squared.
double SNP_mappos (const SNP *snp)
static int SNP_multiplicity (const SNP *snp, int rep)
long SNP_ndx (const SNP *snp)
index of this SNP (begins with 0)
SNP * SNP_new (unsigned nGtype, int bootreps)
Allocate a new SNP, including the arrays used to store genotype data and bootstrap multiplicity values.
int SNP_nGtype (const SNP *snp)
Number of genotypes sampled for this SNP.
int SNP_set (SNP *snp, long ndx, double mappos, const unsigned char *gtype, const Boot *boot, unsigned ploidy)
Initialize a SNP using the data given by the other parameters.
void SNP_show (SNP *snp, FILE *fp)
Print SNP.
void SNPstore_checkin (SNPstore *store, SNP *snp)
Check a SNP back into the store.
SNP * SNPstore_checkout (SNPstore *store)
Obtain a SNP from the store, allocating if necessary.
void SNPstore_free (SNPstore *sp)
Free an object of type SNPstore.
SNPstore * SNPstore_new (unsigned nGtype, int bootreps)
Allocate a new object of type SNPstore.
int Window_advance (Window *window, Tabulation *tab, Boot *boot, long lineno)
Add a new SNP to the window.
SNP * Window_currSNP (Window *window)
Return pointer to current focal SNP.
void Window_free (Window *window)
Free a Window.
int Window_nextSNP (Window *window, Boot *boot)
Get next SNP from input file and link it into the linked list pointed to by window->curr.
Window * Window_new (double width_cm, FILE *ifp, long sampling_interval, unsigned ploidy)
unsigned Window_nGtype (const Window *window)
Return current value of window->nGtype.
long Window_nSNPsRead (const Window *window)
Return the number of SNPs that have been read.
void Window_test (int verbose)
Detailed Description
Header for window.c.
Author
Alan R. Rogers
Copyright
Copyright (c) 2014, Alan R. Rogers roger.nosp@m.s@an.nosp@m.thro..nosp@m.utah.nosp@m..edu. This file is released under the Internet Systems Consortium License, which can be found in file "LICENSE".
Function Documentation
void SNP_clear (SNP * snp)
Set values to initial states.
This function does not initialize snp->prev, because doing so risks a memory leak.
Referenced by SNP_new(), and SNPstore_checkout().
SNP* SNP_connect (SNP * list1, SNP * list2)
Connect list2 to the tail of list1 and return a pointer to list1.
Usage: list1 = SNP_connect(list1, list2)
Parameters
[in] list1,list2 Linked lists of SNPs, which will be concatenated.
Returns
A pointer to the head of the combined list. If list1 is nonNULL, this returned pointer will equal "list1". Otherwise, it will equal "list2". Either way, the returned value is the head of a list that contains all the entries in list 1 followed by all the entries in list 2.
Referenced by SNPstore_checkin().
double SNP_getDsq (double * pqpq, SNP * x, SNP * y, unsigned ploidy)
Calculate D squared.
Use two SNPs to calculate D*D (where D is the standard LD coefficient) and the product of the pq values at the two SNPs. Function also sets the value of *pqpq. This version uses the EM algorithm to get a maximum-likelihood estimate of D. This also provides a ML estimate of Dsq=D*D because of the invariant property of ML estimates.
References DsqData_print(), DsqData::hiD, hiD(), DsqData::loD, loD(), MAKE_PHASED, minimize1D(), DsqData::nGam, DsqData::nUnphased, DsqData::px, DsqData::py, DsqData::tol, trBits(), and UNPHASED_PAIR.
Referenced by Window_advance().
SNP* SNP_new (unsigned nGtype, int bootreps)
Allocate a new SNP, including the arrays used to store genotype data and bootstrap multiplicity values.
In order to improve efficiency, these allocations are all done with a single call to malloc. That way, data for each SNP is in contiguous memory, and we minimize cache misses.
Parameters
[in] nGtype Number of genotypes at each SNP
[in] bootreps Number of bootstrap replicates.
Returns
pointer to newly-allocated SNP.
References SNP_clear().
Referenced by SNPstore_checkout().
int SNP_set (SNP * snp, long ndx, double mappos, const unsigned char * gtype, const Boot * boot, unsigned ploidy)
Initialize a SNP using the data given by the other parameters.
Parameters
[in] ndx SNPs are indexed (numbered) starting with 0. ndx is the index of the current SNP.
[in] mappos position of SNP in units of the recombinational map.
[in] gtype points to a character string representing genotypes
[in,out] boot points to Boot structure, which is used to store information about bootstrap replicates.
[in] ploidy (either 0 or 1)
Returns
1 if the SNP is polymorphic, or 0 if monomorphic.
Referenced by Window_nextSNP().
void SNPstore_checkin (SNPstore * store, SNP * snp)
Check a SNP back into the store.
References SNPstore::head, and SNP_connect().
Referenced by Window_advance().
SNP* SNPstore_checkout (SNPstore * store)
Obtain a SNP from the store, allocating if necessary.
References SNPstore::bootreps, SNPstore::head, SNPstore::nGtype, SNP_clear(), and SNP_new().
Referenced by Window_nextSNP().
SNPstore* SNPstore_new (unsigned nGtype, int bootreps)
Allocate a new object of type SNPstore.
Parameters
nGtype number of genotypes
bootreps number of bootstrap replicates
References SNPstore::bootreps, SNPstore::head, and SNPstore::nGtype.
Referenced by Window_nextSNP().
int Window_advance (Window * window, Tabulation * tab, Boot * boot, long count)
Add a new SNP to the window.
References Window::curr, Dbl_near(), Window::ploidy, Window::sampling_interval, SNP_getDsq(), SNPstore_checkin(), Window::store, Window::width_cm, and Window_nextSNP().
Referenced by threadfun().
int Window_nextSNP (Window * window, Boot * boot)
Get next SNP from input file and link it into the linked list pointed to by window->curr.
Return 0 on success, EOF if end of file is reached, and 1 on any other error.
References Window::curr, Dbl_near(), Gtp_readSNP(), Window::gtype, Window::ifp, Window::nGtype, Window::nSNPs, Window::ploidy, SNP_set(), SNPstore_checkout(), SNPstore_new(), and Window::store.
Referenced by threadfun(), and Window_advance().
long Window_nSNPsRead (const Window * window)
Return the number of SNPs that have been read.
References Window::nSNPs.